"""Stripe payments seed generator — Story 15.7 (Epic 15).

Produces ~90 days of realistic Stripe charges for the local dev/CI loop and the
seed->mart integration test. The rows are the CANONICAL raw shape that
connector._parse_charge() produces (date, charge_id, payment_intent_id,
client_reference_id, revenue, refunds, fees, transaction_count, order_count,
revenue_source_currency) so the golden conformance fixture (AI-54) can be
regenerated by the SAME parse logic, not written by hand.

RUNTIME DEFAULT end_date = date.today() so the Stripe date window aligns with the
Shopify seed (which also defaults to today()). The two generators share the same
window at runtime -> the correlated Stripe charges land on REAL Shopify order dates ->
the integration-test overlap check (Guard A) stays valid indefinitely.

GOLDEN / EXPECTED FIXTURES use FIXTURE_END_DATE (passed explicitly) so the fixture
file is reproducible across runs:
    rows = generate_rows(days=90, end_date=FIXTURE_END_DATE)

PARTIAL CORRELATION WITH THE SHOPIFY SEED (deliberate, for the revenue-dedup proof):
  * a MAJORITY of Stripe charges SETTLE a Shopify order -- they carry the same revenue
    amount and a client_reference_id equal to the Shopify order_id. These are the SAME
    sale seen twice (Stripe payment + Shopify order): summing revenue across the two
    connectors would DOUBLE-COUNT them. The cross_source_revenue view (revenue -> shopify
    priorite 1, stripe priorite 2) picks ONE per day so they count once (AD-4).
  * a MINORITY of Stripe charges are STRIPE-ONLY (SaaS subscriptions / services with no
    Shopify order) -- no client_reference_id join, present only in Stripe. This is why a
    SaaS project can use Stripe as its revenue source of truth without any Shopify boutique.
  Same discipline as the GA4 transactions seed of 17.4 (SUBSET of the Shopify seed's
  transaction_ids). Deterministic (fixed RNG seed).

ALIGNMENT GUARANTEE: the Shopify generator (generate_shopify_seed.py) uses a fixed RNG
seed (15_4_2026) independent of end_date. order_id values are sequential from a fixed
counter, so the same order_ids are produced regardless of which date window is used.
client_reference_id = str(order_id) in the Stripe seed therefore always matches real
order_ids in raw_shopify_orders -- the correlation is REAL (non-tautological) at runtime
because both generators are called with the same end_date (today() by default).

Properties (calibrated to the story ACs):
  * ~90 days, a handful of charges/day with weekday seasonality (weekends lighter).
  * revenue/refunds/fees positive; refunds > 0 on ~7% of charges (DEDICATED column,
    never subtracted from revenue -- decision de story 15.7).
  * fees ~2.9% + 0.25 EUR per charge (a plausible Stripe fee shape; the exact schedule
    is account-specific -- AI-53).
  * client_reference_id present on the Shopify-correlated majority; NULL on Stripe-only.
  * ASCII-only stdout (AI-03).

Usage:
    python generate_stripe_seed.py                 # writes stripe_payments_seed.csv
    python generate_stripe_seed.py --out /tmp/x.csv
    # regenerate golden fixture slice (fixed date):
    python generate_stripe_seed.py --end-date 2026-07-15 --out stripe_payments_seed.csv
"""

from __future__ import annotations

import argparse
import csv
import importlib.util
import os
import random
from datetime import date, timedelta
from pathlib import Path

# Frozen date used ONLY for reproducing golden / expected fixtures (AI-54).
# Pass this explicitly to generate_rows() when regenerating fixture files.
# Do NOT use as a runtime default -- that would misalign with the Shopify seed window.
FIXTURE_END_DATE = date(2026, 7, 15)

WEEKDAY_MULTIPLIERS: dict[int, float] = {
    0: 1.00,  # Monday
    1: 1.04,  # Tuesday
    2: 1.03,  # Wednesday
    3: 1.02,  # Thursday
    4: 1.08,  # Friday
    5: 0.82,  # Saturday
    6: 0.74,  # Sunday
}

# Base number of Stripe-only (SaaS/services) charges on a rank-1.0 weekday.
BASE_STRIPE_ONLY_PER_DAY = 4
# Average charge value band (EUR) for Stripe-only charges.
AOV_RANGE: tuple[float, float] = (19.0, 240.0)
REFUND_PROBABILITY = 0.07           # ~7% of charges carry a (partial) refund
REFUND_FRACTION_RANGE = (0.2, 1.0)  # partial to full refund of the charge value
# Fraction of Shopify (with-txn) orders that ALSO settle through Stripe (majority).
# The rest of the Shopify orders paid via another PSP or are not in Stripe.
SHOPIFY_SETTLED_VIA_STRIPE = 0.80

# Stripe fee shape (AI-53: account-specific; a plausible 2.9% + 0.25 EUR default).
FEE_PERCENT = 0.029
FEE_FIXED = 0.25

COLUMNS = [
    "date",
    "charge_id",
    "payment_intent_id",
    "client_reference_id",
    "revenue",
    "refunds",
    "fees",
    "transaction_count",
    "order_count",
    "revenue_source_currency",
]


def _load_shopify_seed_generator():
    """Import the Shopify seed generator (module-owned) to correlate the Stripe seed.

    The Shopify seed is the SOURCE for the correlated sales; the Stripe seed settles a
    MAJORITY of them (same revenue + client_reference_id = the Shopify order_id) and adds
    a minority of Stripe-only charges. We import it by path (seeds/ is not a package),
    mirroring the GA4-txn / integration-test import pattern of 17.4.
    """
    # __file__ = server/modules/stripe/seeds/generate_stripe_seed.py
    # parents[2] = server/modules ; then shopify/seeds/generate_shopify_seed.py
    shopify_gen_path = (
        Path(__file__).resolve().parents[2] / "shopify" / "seeds" / "generate_shopify_seed.py"
    )
    spec = importlib.util.spec_from_file_location(
        "_shopify_seed_for_stripe", str(shopify_gen_path)
    )
    mod = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(mod)
    return mod


def _fee_for(amount: float) -> float:
    """Plausible Stripe fee (2.9% + 0.25 EUR), rounded to cents. AI-53: account-specific."""
    return round(amount * FEE_PERCENT + FEE_FIXED, 2)


def generate_rows(
    days: int = 90,
    end_date: date | None = None,
    *,
    rng: random.Random | None = None,
    currency: str = "EUR",
    shopify_rows: list[dict] | None = None,
) -> list[dict]:
    """Return deterministic canonical Stripe raw charge rows for the last *days* days.

    Rows match connector._parse_charge() output shape exactly (AI-54 fixture honesty):
    the golden conformance fixture is a SLICE of these rows and its expected_facts are
    produced by connector.transform() over the same rows.

    end_date defaults to date.today() so the Stripe window aligns with the Shopify seed
    (which also defaults to today()). Pass FIXTURE_END_DATE explicitly when regenerating
    golden / expected fixture files to keep them reproducible.
    """
    if end_date is None:
        # Runtime default: today() so the window aligns with the Shopify seed loader.
        # For fixture regeneration pass FIXTURE_END_DATE explicitly.
        end_date = date.today()
    if rng is None:
        # Fixed seed -> deterministic seed data (reproducible fixtures/tests).
        rng = random.Random(15_7_2026)

    # 1. Correlated part: settle a MAJORITY of the Shopify orders that HAVE a transaction_id.
    if shopify_rows is None:
        shopify_gen = _load_shopify_seed_generator()
        # SAME end_date as passed/defaulted above so both date windows align at runtime.
        # The Shopify generator uses a fixed internal RNG seed (15_4_2026) -> order_ids
        # are deterministic regardless of end_date -> client_reference_id joins are REAL.
        shopify_rows = shopify_gen.generate_rows(days=days, end_date=end_date)

    start_date = end_date - timedelta(days=days)
    charge_seq = 5000000000
    rows: list[dict] = []

    for r in shopify_rows:
        txn = r.get("transaction_id")
        if txn is None:
            # No Shopify transaction id -> not settled through the correlated Stripe path.
            continue
        if rng.random() >= SHOPIFY_SETTLED_VIA_STRIPE:
            continue  # this Shopify order was NOT paid via Stripe in the seed.
        charge_seq += 1
        revenue = round(float(r["revenue"]), 2)
        refunds = 0.0
        if rng.random() < REFUND_PROBABILITY:
            frac = rng.uniform(*REFUND_FRACTION_RANGE)
            refunds = round(revenue * frac, 2)
        rows.append(
            {
                "date": r["date"],
                "charge_id": f"ch_{charge_seq}",
                "payment_intent_id": f"pi_{charge_seq}",
                # DEDUP KEY: client_reference_id == the Shopify order_id -> the SAME sale.
                "client_reference_id": str(r["order_id"]),
                "revenue": revenue,
                "refunds": refunds,
                "fees": _fee_for(revenue),
                "transaction_count": 1,
                "order_count": 1,
                "revenue_source_currency": currency,
            }
        )

    # 2. Stripe-only part: SaaS/services charges with no Shopify order (no join key).
    for offset in range(days):
        day = start_date + timedelta(days=offset)
        multiplier = WEEKDAY_MULTIPLIERS[day.weekday()]
        n_charges = max(
            1, round(BASE_STRIPE_ONLY_PER_DAY * multiplier * rng.uniform(0.8, 1.2))
        )
        for _ in range(n_charges):
            charge_seq += 1
            revenue = round(rng.uniform(*AOV_RANGE), 2)
            refunds = 0.0
            if rng.random() < REFUND_PROBABILITY:
                frac = rng.uniform(*REFUND_FRACTION_RANGE)
                refunds = round(revenue * frac, 2)
            rows.append(
                {
                    "date": day.isoformat(),
                    "charge_id": f"ch_{charge_seq}",
                    "payment_intent_id": f"pi_{charge_seq}",
                    # Stripe-only: no Shopify order -> no GA4-joinable client_reference_id.
                    "client_reference_id": None,
                    "revenue": revenue,
                    "refunds": refunds,
                    "fees": _fee_for(revenue),
                    "transaction_count": 1,
                    "order_count": 1,
                    "revenue_source_currency": currency,
                }
            )

    # Stable ordering by (date, charge_id) so the fixture slice is deterministic.
    rows.sort(key=lambda x: (x["date"], x["charge_id"]))
    return rows


def write_csv(rows: list[dict], path: str | os.PathLike) -> None:
    """Write rows to *path* as a CSV with header (None -> blank cell)."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=COLUMNS)
        writer.writeheader()
        for r in rows:
            row = {k: ("" if r.get(k) is None else r.get(k)) for k in COLUMNS}
            writer.writerow(row)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Stripe payments seed CSV")
    parser.add_argument("--out", default=None, help="Output CSV path (defaults next to this file)")
    parser.add_argument("--days", type=int, default=90, help="Number of days to seed")
    parser.add_argument(
        "--end-date",
        default=None,
        help=(
            "End date YYYY-MM-DD (default: today). Pass 2026-07-15 to regenerate "
            "the golden fixture with the frozen FIXTURE_END_DATE."
        ),
    )
    args = parser.parse_args()

    end_date: date | None = None
    if args.end_date:
        end_date = date.fromisoformat(args.end_date)

    here = Path(__file__).parent
    out = args.out or str(here / "stripe_payments_seed.csv")
    rows = generate_rows(days=args.days, end_date=end_date)
    write_csv(rows, out)
    correlated = sum(1 for r in rows if r["client_reference_id"] is not None)
    total_rev = sum(r["revenue"] for r in rows)
    print(f"Generated {len(rows)} rows -> {out}")
    print(
        f"shopify-correlated charges: {correlated}/{len(rows)}  "
        f"total revenue: {total_rev:.2f}"
    )


if __name__ == "__main__":
    main()
