"""TikTok Ads seed generator — Story 15.2 (Epic 15).

Produces multi-day (>=35) TikTok Ads rows for the local dev/CI loop, the seed->mart
integration test and the golden conformance fixture (AI-54). The rows are the CANONICAL
raw shape that connector._parse_report_row() produces (date, data_level, campaign_id,
campaign_name, adgroup_id, adgroup_name, ad_id, spend, impressions, clicks, conversions,
cost_source_currency) so the golden fixture can be regenerated by the SAME parse logic,
not written by hand.

review-15-2 F-1: the generator emits the THREE grains (campaign / adgroup / ad daily)
COEXISTING in the same raw table, each stamped with its data_level (AUCTION_CAMPAIGN |
AUCTION_ADGROUP | AUCTION_AD). The ad-grain rows are generated first; the adgroup and
campaign grains are EXACT roll-ups of them, so campaign total == sum of adgroups == sum
of ads per (project, date, metric). This is precisely the coexistence that used to
double-count the campaign_id series before the data_level filter existed.

Properties (calibrated to the story ACs):
  * >=35 days, a handful of campaigns/day with weekday seasonality (weekends lighter).
  * spend/impressions/clicks/conversions are DETERMINISTIC (fixed RNG seed) and coherent
    (clicks <= impressions, conversions <= clicks).
  * campaign-grain rows: adgroup_id / ad_id are None (data_level=AUCTION_CAMPAIGN);
    adgroup-grain rows: ad_id None (AUCTION_ADGROUP); ad-grain rows carry all three ids
    (AUCTION_AD). The staging grain key stays unique via COALESCE + data_level.
  * conversions are CLAIMED by the channel (attribution window declared in the manifest);
    they never enter a cross-source total without the dedup rule.
  * ASCII-only stdout (AI-03).

Usage:
    python generate_tiktok_seed.py                 # writes tiktok_ads_seed.csv
    python generate_tiktok_seed.py --out /tmp/x.csv
    python generate_tiktok_seed.py --grains campaign   # campaign grain only (legacy)
"""

from __future__ import annotations

import argparse
import csv
import os
import random
from datetime import date, timedelta
from pathlib import Path

WEEKDAY_MULTIPLIERS: dict[int, float] = {
    0: 1.00,  # Monday
    1: 1.04,  # Tuesday
    2: 1.06,  # Wednesday
    3: 1.05,  # Thursday
    4: 1.12,  # Friday
    5: 0.85,  # Saturday
    6: 0.78,  # Sunday
}

# A small stable roster of campaigns (campaign-grain profile: one row per campaign/day).
CAMPAIGNS: list[tuple[str, str]] = [
    ("1770000000000000001", "Toorow - Notoriete FR"),
    ("1770000000000000002", "Toorow - Conversion Web"),
    ("1770000000000000003", "Toorow - Retargeting Panier"),
]

# review-15-2 F-1: each campaign fans out into this many ad groups, each into this many
# ads. The ad-grain rows are generated first and rolled up so the grains reconcile EXACTLY.
ADGROUPS_PER_CAMPAIGN = 2
ADS_PER_ADGROUP = 2

# data_level values stamped per grain (mirror connector._DATA_LEVEL_BY_PROFILE).
DATA_LEVEL_CAMPAIGN = "AUCTION_CAMPAIGN"
DATA_LEVEL_ADGROUP = "AUCTION_ADGROUP"
DATA_LEVEL_AD = "AUCTION_AD"

# Per-campaign daily spend band (EUR) and funnel ratios.
SPEND_RANGE: tuple[float, float] = (45.0, 380.0)
CPM_RANGE: tuple[float, float] = (4.0, 9.0)      # cost per mille -> impressions
CTR_RANGE: tuple[float, float] = (0.008, 0.028)  # click-through rate -> clicks
CVR_RANGE: tuple[float, float] = (0.02, 0.09)    # conversion rate on clicks

COLUMNS = [
    "date",
    "data_level",
    "campaign_id",
    "campaign_name",
    "adgroup_id",
    "adgroup_name",
    "ad_id",
    "spend",
    "impressions",
    "clicks",
    "conversions",
    "cost_source_currency",
]


def generate_rows(
    days: int = 40,
    end_date: date | None = None,
    *,
    rng: random.Random | None = None,
    currency: str = "EUR",
) -> list[dict]:
    """Return deterministic canonical TikTok raw campaign-grain rows for *days* days.

    Rows match connector._parse_report_row() output shape exactly (AI-54 fixture
    honesty): the golden conformance fixture is a SLICE of the API-shaped payload and
    its expected_facts are produced by connector.transform() over the same rows.
    Each row is stamped data_level=AUCTION_CAMPAIGN (F-1). For the three-grain coexistence
    seed (the double-count reconciliation case) use generate_multigrain_rows().
    """
    if end_date is None:
        end_date = date.today()
    if rng is None:
        # Fixed seed -> deterministic seed data (reproducible fixtures/tests).
        rng = random.Random(15_2_2026)

    start_date = end_date - timedelta(days=days)
    rows: list[dict] = []

    for offset in range(days):
        day = start_date + timedelta(days=offset)
        multiplier = WEEKDAY_MULTIPLIERS[day.weekday()]

        for campaign_id, campaign_name in CAMPAIGNS:
            spend = round(rng.uniform(*SPEND_RANGE) * multiplier, 2)
            cpm = rng.uniform(*CPM_RANGE)
            impressions = max(1, int(spend / cpm * 1000))
            clicks = max(0, int(impressions * rng.uniform(*CTR_RANGE)))
            conversions = max(0, int(clicks * rng.uniform(*CVR_RANGE)))

            rows.append(
                {
                    "date": day.isoformat(),
                    "data_level": DATA_LEVEL_CAMPAIGN,
                    "campaign_id": campaign_id,
                    "campaign_name": campaign_name,
                    # Campaign-grain profile: no adgroup/ad detail (None -> NULL).
                    "adgroup_id": None,
                    "adgroup_name": None,
                    "ad_id": None,
                    "spend": spend,
                    "impressions": impressions,
                    "clicks": clicks,
                    "conversions": conversions,
                    "cost_source_currency": currency,
                }
            )
    return rows


def generate_multigrain_rows(
    days: int = 40,
    end_date: date | None = None,
    *,
    rng: random.Random | None = None,
    currency: str = "EUR",
) -> list[dict]:
    """Return the THREE grains (campaign / adgroup / ad daily) COEXISTING in one raw set.

    review-15-2 F-1: this is the case that double-counted the campaign_id series before
    the data_level filter existed. The ad-grain rows are generated first; the adgroup and
    campaign grains are EXACT integer roll-ups, so per (project, date, metric):
        SUM over campaign grain == SUM over adgroup grain == SUM over ad grain.
    Each grain is stamped its data_level so the mart reads only its own rows.
    """
    if end_date is None:
        end_date = date.today()
    if rng is None:
        rng = random.Random(15_2_2026)

    start_date = end_date - timedelta(days=days)
    rows: list[dict] = []

    for offset in range(days):
        day = start_date + timedelta(days=offset)
        multiplier = WEEKDAY_MULTIPLIERS[day.weekday()]

        for campaign_id, campaign_name in CAMPAIGNS:
            # Accumulators rolled up from the finest (ad) grain so totals reconcile exactly.
            camp_spend = 0.0
            camp_impr = camp_clicks = camp_conv = 0
            adgroup_rows: list[dict] = []
            ad_rows: list[dict] = []

            for ag_ix in range(ADGROUPS_PER_CAMPAIGN):
                adgroup_id = f"{campaign_id}{ag_ix + 1:02d}"
                adgroup_name = f"{campaign_name} / AG{ag_ix + 1}"
                ag_spend = 0.0
                ag_impr = ag_clicks = ag_conv = 0

                for ad_ix in range(ADS_PER_ADGROUP):
                    ad_id = f"{adgroup_id}{ad_ix + 1:02d}"
                    spend = round(rng.uniform(*SPEND_RANGE) / 4 * multiplier, 2)
                    cpm = rng.uniform(*CPM_RANGE)
                    impressions = max(1, int(spend / cpm * 1000))
                    clicks = max(0, int(impressions * rng.uniform(*CTR_RANGE)))
                    conversions = max(0, int(clicks * rng.uniform(*CVR_RANGE)))

                    ad_rows.append(
                        {
                            "date": day.isoformat(),
                            "data_level": DATA_LEVEL_AD,
                            "campaign_id": campaign_id,
                            "campaign_name": campaign_name,
                            "adgroup_id": adgroup_id,
                            "adgroup_name": adgroup_name,
                            "ad_id": ad_id,
                            "spend": spend,
                            "impressions": impressions,
                            "clicks": clicks,
                            "conversions": conversions,
                            "cost_source_currency": currency,
                        }
                    )
                    ag_spend += spend
                    ag_impr += impressions
                    ag_clicks += clicks
                    ag_conv += conversions

                adgroup_rows.append(
                    {
                        "date": day.isoformat(),
                        "data_level": DATA_LEVEL_ADGROUP,
                        "campaign_id": campaign_id,
                        "campaign_name": campaign_name,
                        "adgroup_id": adgroup_id,
                        "adgroup_name": adgroup_name,
                        # Adgroup-grain profile: no ad detail (None -> NULL).
                        "ad_id": None,
                        "spend": round(ag_spend, 2),
                        "impressions": ag_impr,
                        "clicks": ag_clicks,
                        "conversions": ag_conv,
                        "cost_source_currency": currency,
                    }
                )
                camp_spend += ag_spend
                camp_impr += ag_impr
                camp_clicks += ag_clicks
                camp_conv += ag_conv

            # Campaign-grain row = exact roll-up of its adgroups (== sum of its ads).
            rows.append(
                {
                    "date": day.isoformat(),
                    "data_level": DATA_LEVEL_CAMPAIGN,
                    "campaign_id": campaign_id,
                    "campaign_name": campaign_name,
                    "adgroup_id": None,
                    "adgroup_name": None,
                    "ad_id": None,
                    "spend": round(camp_spend, 2),
                    "impressions": camp_impr,
                    "clicks": camp_clicks,
                    "conversions": camp_conv,
                    "cost_source_currency": currency,
                }
            )
            rows.extend(adgroup_rows)
            rows.extend(ad_rows)
    return rows


def write_csv(rows: list[dict], path: str | os.PathLike) -> None:
    """Write rows to *path* as a CSV with header (None -> blank cell)."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=COLUMNS)
        writer.writeheader()
        for r in rows:
            row = {k: ("" if r.get(k) is None else r.get(k)) for k in COLUMNS}
            writer.writerow(row)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate TikTok Ads seed CSV")
    parser.add_argument("--out", default=None, help="Output CSV path (defaults next to this file)")
    parser.add_argument("--days", type=int, default=40, help="Number of days to seed")
    parser.add_argument(
        "--grains",
        choices=["campaign", "multi"],
        default="campaign",
        help="campaign = campaign grain only (default); multi = 3 grains coexisting (F-1)",
    )
    args = parser.parse_args()

    here = Path(__file__).parent
    out = args.out or str(here / "tiktok_ads_seed.csv")
    if args.grains == "campaign":
        rows = generate_rows(days=args.days)
    else:
        rows = generate_multigrain_rows(days=args.days)
    write_csv(rows, out)
    # Campaign-grain rows carry the reconciled day totals -> sum only them to avoid
    # triple-counting across coexisting grains in this human-readable summary.
    camp_rows = [r for r in rows if r["data_level"] == DATA_LEVEL_CAMPAIGN]
    total_spend = sum(r["spend"] for r in camp_rows)
    total_conv = sum(r["conversions"] for r in camp_rows)
    print(f"Generated {len(rows)} rows ({args.grains} grains) -> {out}")
    print(f"campaign-grain total spend: {total_spend:.2f}  total conversions: {total_conv}")


if __name__ == "__main__":
    main()
