"""`screens/pages.md` names every addressable page -- or it names nothing.

WHY THIS FILE EXISTS. `screens/pages.md` is generated by
`python scripts/screens.py pages` and read by people deciding what to build. Two
guards already exist for its siblings (`test_screen_expectations.py`,
`test_surface_state.py`) and this page had NONE: measured 2026-08-07,
`grep -rln "pages.md" server/tests/` returned nothing. Story 58.6 added the
`Cost` tab to `navigation.ts`, the page went stale the same minute, and no test
in the repository could say so. A generated inventory nobody checks is believed
exactly as long as it is wrong.

WHAT IT COMPARES, AND WHY NOT THE WHOLE FILE. The set of ADDRESSABLE PAGES --
one row per `section` and per `section/o/type/tab` -- against what
`navigation.ts` declares. Not the file byte for byte: the page also carries a
`draws` column counting how many files of a section's tree name each tab, and
that number moves whenever anybody anywhere adds a component. A byte comparison
would go red for work that has nothing to do with the inventory, which is how a
guard gets ignored and then deleted. The set is the claim; the counts are
commentary.

IT COMPARES, IT DOES NOT REGENERATE. A guard that rewrote the file could never
fail. When it goes red, run the one command in the message.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).parents[3]
sys.path.insert(0, str(_REPO_ROOT / "scripts"))

screens = pytest.importorskip("screens")

_PAGES_MD = _REPO_ROOT / "screens" / "pages.md"

#: `| `data/datastreams/o/datastream/cost` | tab | explicit | 3 | ... |`
_ROW = re.compile(r"^\| `([^`]+)` \| (section|tab) \|", re.M)

_REGENERATE = "  python scripts/screens.py pages"


def _declared() -> set[str]:
    """Every page `navigation.ts` promises, at the grain a person clicks."""
    pages: set[str] = set()
    for screen in screens.workspaces():
        pages.add(screen.id)
        for obj in screen.objects:
            if not obj["tabs"]:
                pages.add(f"{screen.id}/o/{obj['type']}")
                continue
            for tab in obj["tabs"]:
                pages.add(f"{screen.id}/o/{obj['type']}/{tab}")
    return pages


def _inventoried() -> set[str]:
    return {match.group(1) for match in _ROW.finditer(_PAGES_MD.read_text(encoding="utf-8"))}


def test_the_inventory_names_every_page_the_navigation_contract_declares() -> None:
    declared, inventoried = _declared(), _inventoried()

    missing = sorted(declared - inventoried)
    # The global surfaces (`account/...`, `organization-settings/...`) are rows of
    # the page too and are not declared by `WORKSPACES`, so only one direction of
    # the comparison is total. A row that names a workspace page the contract does
    # not declare is still a phantom, and is caught here.
    phantom = sorted(
        page
        for page in inventoried - declared
        if page.split("/")[0] in {screen.surface for screen in screens.workspaces()}
    )
    assert not missing and not phantom, (
        "`screens/pages.md` no longer describes this console.\n"
        f"  declared and NOT in the inventory ({len(missing)}): {missing}\n"
        f"  in the inventory and NOT declared ({len(phantom)}): {phantom}\n\n"
        "Regenerate it:\n" + _REGENERATE + "\n\n"
        "A page missing from the inventory is worse than a stale count: the file is "
        "read to decide what is left to build, so an address nobody listed is work "
        "nobody plans."
    )


def test_the_conditional_tab_is_inventoried_like_any_other() -> None:
    """`Cost` exists only under a capability, and it is still an ADDRESS.

    A conditional tab left out of the inventory would read as a page that does not
    exist, which is the opposite of what the amendment « Une capacité activée
    AJOUTE son onglet » says: it exists, for the Projects that opened it.
    """
    assert "data/datastreams/o/datastream/cost" in _inventoried()
    assert "data/datastreams/o/datastream/cost" in _declared()


def test_the_guard_is_not_vacuous() -> None:
    """Both sides really carry pages -- an empty comparison passes anything."""
    declared, inventoried = _declared(), _inventoried()

    assert len(declared) > 100, len(declared)
    assert len(inventoried) > 100, len(inventoried)
    # And the row shape is the one being parsed, or the comparison would be an
    # accident: a page id is a slash-separated path, never a markdown cell.
    assert all("|" not in page for page in inventoried)
