"""Deterministic builder for pinterest-ads official_fields.json (Story 26.3).

This script is the AUDITABLE SOURCE for the committed official snapshot. It is
committed alongside its outputs (official_fields.json + the regenerated
``field_compatibility`` rules inside catalog_sources.json) so a reviewer can
see exactly how the curated column space was derived from the official
Pinterest REST API v5 OpenAPI spec (pinterest/api-description, pinned 5.28.0)
recorded in catalog_sources.json.

It is pure-Python, deterministic (no network, no clock), and byte-stable:
running it again reproduces both outputs exactly.

Derivation summary (see catalog_sources.json "_derivation"):
  - ASYNC_COLUMNS = the INTEGRAL ``ReportingColumnAsync`` enum (626 values, in
    spec order -- research dossier Annex A, fetched 2026-07-21). ZERO
    truncation (story 26.3 hard rule: 627 columns, zero planned).
  - SYNC_ALSO   = the 184 columns also present in ``ReportingColumnSync``
    (Annex A ``[S]`` markers). ReportingColumnSync totals 185 values: these
    184 + the single sync-only column below.
  - SYNC_ONLY   = ``QUIZ_PIN_RESULT_OPEN`` -- the ONE column of the sync enum
    absent from the async enum. Union async+sync = 627 official columns.
  - DIMENSIONS  = the 53 entity-attribute columns (Annex A ``[dim]`` markers,
    curated: ids/names/statuses/labels/caps/product-item attributes). They are
    declared kind=dimension; every other enum value is a metric.
  - ``date``    = the ONE structural grain dimension of the report response
    (``DATE`` key, granularity DAY). It is NOT an enum value -- it is never
    sent in ``columns`` -- so the catalog totals 628 entries = 627 official
    columns + this grain dimension.
  - NO EXPANSION RULE: unlike Meta action-families, Pinterest pre-flattens
    every conversion family x attribution split x unit variant and the
    99-column device-path family directly into the enum. The enum IS the flat
    catalog.
  - Sections are assigned from the ordered name-family rules below (the
    OpenAPI spec carries no sections); micro-currency columns
    (*_IN_MICRO_DOLLAR) carry the ``value/1e6`` landing marker in their
    description -- the CONNECTOR derives its unit-conversion set from that
    catalog marker, never from an id-suffix heuristic (google-ads review
    lesson, 26.2).
  - This script ALSO regenerates catalog_sources.json's ``field_compatibility``
    rules (core schema "1", one selectable_set rule per whitelisted report
    level) so the pre-call refusal contract can never drift from the column
    space.

Run (orchestrator, local only -- outputs are committed):
    uv run python server/modules/pinterest-ads/catalog_sources/build_official_fields.py
"""

from __future__ import annotations

import json
from pathlib import Path

# ---------------------------------------------------------------------------
# Sections (exactly the section_tier_map keys in catalog_sources.json).
# ---------------------------------------------------------------------------
S_SPEND = "SPEND"
S_IMPRESSION = "IMPRESSION"
S_CLICKTHROUGH = "CLICKTHROUGH"
S_PERFORMANCE = "PERFORMANCE"
S_ENTITY = "ENTITY"
S_TIME = "TIME"
S_ENGAGEMENT = "ENGAGEMENT"
S_CONVERSION = "CONVERSION"
S_CONVERSION_VALUE = "CONVERSION VALUE"
S_WEB_SESSIONS = "WEB SESSIONS"
S_VIDEO = "VIDEO"
S_DEVICE_PATH = "CONVERSION DEVICE PATH"
S_PRODUCT_ITEM = "PRODUCT ITEM"
S_COLLECTION = "COLLECTION"

# ---------------------------------------------------------------------------
# 1. ASYNC_COLUMNS -- the INTEGRAL ReportingColumnAsync enum (626 values, in
#    OpenAPI 5.28.0 spec order; research dossier Annex A). Zero truncation.
# ---------------------------------------------------------------------------
ASYNC_COLUMNS: tuple[str, ...] = (
    "SPEND_IN_MICRO_DOLLAR",
    "ADS_CREDIT_SPEND_IN_MICRO_DOLLAR",
    "ADS_CREDIT_SPEND_IN_DOLLAR",
    "PAID_IMPRESSION",
    "SPEND_IN_DOLLAR",
    "CPC_IN_MICRO_DOLLAR",
    "ECPC_IN_MICRO_DOLLAR",
    "ECPC_IN_DOLLAR",
    "CTR",
    "ECTR",
    "OUTBOUND_CTR",
    "OUTBOUND_CTR_1",
    "COST_PER_OUTBOUND_CLICK",
    "CAMPAIGN_NAME",
    "CAMPAIGN_STATUS",
    "CAMPAIGN_BRAND_LABEL",
    "CAMPAIGN_CUSTOM_LABELS",
    "PIN_PROMOTION_STATUS",
    "AD_STATUS",
    "PIN_ID",
    "TOTAL_ENGAGEMENT",
    "ENGAGEMENT_1",
    "ENGAGEMENT_2",
    "ECPE_IN_DOLLAR",
    "ENGAGEMENT_RATE",
    "EENGAGEMENT_RATE",
    "ECPM_IN_MICRO_DOLLAR",
    "REPIN_RATE",
    "CTR_2",
    "CAMPAIGN",
    "CAMPAIGN_ID",
    "ADVERTISER_ID",
    "AD_ACCOUNT_ID",
    "PIN_PROMOTION_ID",
    "AD_ID",
    "AD_GROUP_ID",
    "CAMPAIGN_ENTITY_STATUS",
    "CAMPAIGN_MANAGED_STATUS",
    "CAMPAIGN_OBJECTIVE_TYPE",
    "CPM_IN_MICRO_DOLLAR",
    "CPM_IN_DOLLAR",
    "AD_GROUP_NAME",
    "AD_GROUP_STATUS",
    "AD_GROUP_BUDGET_TYPE",
    "AD_GROUP_BUDGET_IN_LOCAL_CURRENCY",
    "AD_GROUP_ENTITY_STATUS",
    "AD_GROUP_BID_MULTIPLIER",
    "PRODUCT_GROUP_ID",
    "PRODUCT_GROUP_STATUS",
    "PROMO_ID",
    "PROMO_NAME",
    "PRODUCT_ITEM_NAME",
    "PRODUCT_ITEM_IMAGE_URL",
    "PRODUCT_ITEM_PRICE",
    "PRODUCT_ITEM_PRODUCT_URL",
    "PRODUCT_ITEM_PIN_URL",
    "PRODUCT_ITEM_BRAND",
    "PRODUCT_ITEM_DESCRIPTION",
    "PRODUCT_ITEM_SALE_PRICE",
    "PRODUCT_ITEM_PRODUCT_TYPE",
    "PRODUCT_ITEM_PRODUCT_CATEGORY",
    "PRODUCT_ITEM_CURRENCY",
    "ORDER_LINE_ID",
    "ORDER_LINE_NAME",
    "CLICKTHROUGH_1",
    "REPIN_1",
    "IMPRESSION_1",
    "IMPRESSION_1_GROSS",
    "CLICKTHROUGH_1_GROSS",
    "OUTBOUND_CLICK_1",
    "CLICKTHROUGH_2",
    "REPIN_2",
    "IMPRESSION_2",
    "OUTBOUND_CLICK_2",
    "COLLECTION_PIN_ITEM_IMPRESSION_1",
    "COLLECTION_PIN_ITEM_IMPRESSION_2",
    "TOTAL_COLLECTION_PIN_ITEM_IMPRESSION",
    "COLLECTION_PIN_ITEM_CLICKTHROUGH_1",
    "COLLECTION_PIN_ITEM_CLICKTHROUGH_2",
    "TOTAL_COLLECTION_PIN_ITEM_CLICKTHROUGH",
    "TOTAL_CLICKTHROUGH",
    "TOTAL_IMPRESSION",
    "TOTAL_IMPRESSION_USER",
    "TOTAL_IMPRESSION_FREQUENCY",
    "COST_PER_OUTBOUND_CLICK_IN_DOLLAR",
    "COST_PER_OUTBOUND_CLICK_IN_DOLLAR_1",
    "TOTAL_ENGAGEMENT_PAGE_VISIT",
    "TOTAL_ENGAGEMENT_SIGNUP",
    "TOTAL_ENGAGEMENT_CHECKOUT",
    "TOTAL_ENGAGEMENT_CUSTOM",
    "TOTAL_ENGAGEMENT_ADD_TO_CART",
    "TOTAL_ENGAGEMENT_LEAD",
    "TOTAL_ENGAGEMENT_SEARCH",
    "TOTAL_ENGAGEMENT_WATCH_VIDEO",
    "TOTAL_ENGAGEMENT_VIEW_CATEGORY",
    "TOTAL_ENGAGEMENT_APP_INSTALL",
    "TOTAL_ENGAGEMENT_UNKNOWN",
    "TOTAL_CLICK_PAGE_VISIT",
    "TOTAL_CLICK_SIGNUP",
    "TOTAL_CLICK_CHECKOUT",
    "TOTAL_CLICK_CUSTOM",
    "TOTAL_CLICK_ADD_TO_CART",
    "TOTAL_CLICK_LEAD",
    "TOTAL_CLICK_SEARCH",
    "TOTAL_CLICK_WATCH_VIDEO",
    "TOTAL_CLICK_VIEW_CATEGORY",
    "TOTAL_CLICK_APP_INSTALL",
    "TOTAL_CLICK_UNKNOWN",
    "TOTAL_VIEW_PAGE_VISIT",
    "TOTAL_VIEW_SIGNUP",
    "TOTAL_VIEW_CHECKOUT",
    "TOTAL_VIEW_CUSTOM",
    "TOTAL_VIEW_ADD_TO_CART",
    "TOTAL_VIEW_LEAD",
    "TOTAL_VIEW_SEARCH",
    "TOTAL_VIEW_WATCH_VIDEO",
    "TOTAL_VIEW_VIEW_CATEGORY",
    "TOTAL_VIEW_APP_INSTALL",
    "TOTAL_VIEW_UNKNOWN",
    "TOTAL_CONVERSIONS",
    "TOTAL_ENGAGEMENT_PAGE_VISIT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ENGAGEMENT_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ENGAGEMENT_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ENGAGEMENT_CUSTOM_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ENGAGEMENT_ADD_TO_CART_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ENGAGEMENT_LEAD_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ENGAGEMENT_SEARCH_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ENGAGEMENT_WATCH_VIDEO_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ENGAGEMENT_VIEW_CATEGORY_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ENGAGEMENT_APP_INSTALL_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ENGAGEMENT_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CLICK_PAGE_VISIT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CLICK_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CLICK_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CLICK_CUSTOM_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CLICK_ADD_TO_CART_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CLICK_LEAD_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CLICK_SEARCH_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CLICK_WATCH_VIDEO_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CLICK_VIEW_CATEGORY_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CLICK_APP_INSTALL_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CLICK_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_VIEW_PAGE_VISIT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_VIEW_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_VIEW_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_VIEW_CUSTOM_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_VIEW_ADD_TO_CART_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_VIEW_LEAD_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_VIEW_SEARCH_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_VIEW_WATCH_VIDEO_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_VIEW_VIEW_CATEGORY_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_VIEW_APP_INSTALL_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_VIEW_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CONVERSIONS_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ENGAGEMENT_PAGE_VISIT_QUANTITY",
    "TOTAL_ENGAGEMENT_SIGNUP_QUANTITY",
    "TOTAL_ENGAGEMENT_CHECKOUT_QUANTITY",
    "TOTAL_ENGAGEMENT_CUSTOM_QUANTITY",
    "TOTAL_ENGAGEMENT_ADD_TO_CART_QUANTITY",
    "TOTAL_ENGAGEMENT_LEAD_QUANTITY",
    "TOTAL_ENGAGEMENT_SEARCH_QUANTITY",
    "TOTAL_ENGAGEMENT_WATCH_VIDEO_QUANTITY",
    "TOTAL_ENGAGEMENT_VIEW_CATEGORY_QUANTITY",
    "TOTAL_ENGAGEMENT_UNKNOWN_QUANTITY",
    "TOTAL_CLICK_PAGE_VISIT_QUANTITY",
    "TOTAL_CLICK_SIGNUP_QUANTITY",
    "TOTAL_CLICK_CHECKOUT_QUANTITY",
    "TOTAL_CLICK_CUSTOM_QUANTITY",
    "TOTAL_CLICK_ADD_TO_CART_QUANTITY",
    "TOTAL_CLICK_LEAD_QUANTITY",
    "TOTAL_CLICK_SEARCH_QUANTITY",
    "TOTAL_CLICK_WATCH_VIDEO_QUANTITY",
    "TOTAL_CLICK_VIEW_CATEGORY_QUANTITY",
    "TOTAL_CLICK_UNKNOWN_QUANTITY",
    "TOTAL_VIEW_PAGE_VISIT_QUANTITY",
    "TOTAL_VIEW_SIGNUP_QUANTITY",
    "TOTAL_VIEW_CHECKOUT_QUANTITY",
    "TOTAL_VIEW_CUSTOM_QUANTITY",
    "TOTAL_VIEW_ADD_TO_CART_QUANTITY",
    "TOTAL_VIEW_LEAD_QUANTITY",
    "TOTAL_VIEW_SEARCH_QUANTITY",
    "TOTAL_VIEW_WATCH_VIDEO_QUANTITY",
    "TOTAL_VIEW_VIEW_CATEGORY_QUANTITY",
    "TOTAL_VIEW_UNKNOWN_QUANTITY",
    "TOTAL_CONVERSIONS_QUANTITY",
    "TOTAL_WEB_SESSIONS",
    "WEB_SESSIONS_1",
    "WEB_SESSIONS_2",
    "ONSITE_CHECKOUTS_1",
    "PIN_PROMOTION_NAME",
    "AD_NAME",
    "CAMPAIGN_LIFETIME_SPEND_CAP",
    "AD_GROUP_OPTIMIZATION",
    "CAMPAIGN_DAILY_SPEND_CAP",
    "CAMPAIGN_BUDGET_OPTIMIZATION",
    "IS_CATALOG_CREATIVE_CAMPAIGN",
    "IS_PREMIERE_CAMPAIGN",
    "TOTAL_PAGE_VISIT_DESKTOP_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_PAGE_VISIT_DESKTOP_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_PAGE_VISIT_DESKTOP_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_PAGE_VISIT_MOBILE_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_PAGE_VISIT_MOBILE_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_PAGE_VISIT_MOBILE_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_PAGE_VISIT_TABLET_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_PAGE_VISIT_TABLET_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_PAGE_VISIT_TABLET_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_SIGNUP_DESKTOP_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_SIGNUP_DESKTOP_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_SIGNUP_DESKTOP_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_SIGNUP_MOBILE_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_SIGNUP_MOBILE_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_SIGNUP_MOBILE_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_SIGNUP_TABLET_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_SIGNUP_TABLET_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_SIGNUP_TABLET_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_CHECKOUT_DESKTOP_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_CHECKOUT_DESKTOP_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_CHECKOUT_DESKTOP_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_CHECKOUT_MOBILE_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_CHECKOUT_MOBILE_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_CHECKOUT_MOBILE_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_CHECKOUT_TABLET_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_CHECKOUT_TABLET_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_CHECKOUT_TABLET_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_CUSTOM_DESKTOP_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_CUSTOM_DESKTOP_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_CUSTOM_DESKTOP_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_CUSTOM_MOBILE_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_CUSTOM_MOBILE_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_CUSTOM_MOBILE_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_CUSTOM_TABLET_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_CUSTOM_TABLET_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_CUSTOM_TABLET_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_ADD_TO_CART_DESKTOP_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_ADD_TO_CART_DESKTOP_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_ADD_TO_CART_DESKTOP_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_ADD_TO_CART_MOBILE_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_ADD_TO_CART_MOBILE_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_ADD_TO_CART_MOBILE_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_ADD_TO_CART_TABLET_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_ADD_TO_CART_TABLET_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_ADD_TO_CART_TABLET_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_LEAD_DESKTOP_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_LEAD_DESKTOP_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_LEAD_DESKTOP_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_LEAD_MOBILE_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_LEAD_MOBILE_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_LEAD_MOBILE_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_LEAD_TABLET_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_LEAD_TABLET_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_LEAD_TABLET_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_SEARCH_DESKTOP_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_SEARCH_DESKTOP_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_SEARCH_DESKTOP_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_SEARCH_MOBILE_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_SEARCH_MOBILE_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_SEARCH_MOBILE_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_SEARCH_TABLET_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_SEARCH_TABLET_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_SEARCH_TABLET_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_WATCH_VIDEO_DESKTOP_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_WATCH_VIDEO_DESKTOP_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_WATCH_VIDEO_DESKTOP_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_WATCH_VIDEO_MOBILE_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_WATCH_VIDEO_MOBILE_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_WATCH_VIDEO_MOBILE_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_WATCH_VIDEO_TABLET_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_WATCH_VIDEO_TABLET_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_WATCH_VIDEO_TABLET_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_VIEW_CATEGORY_DESKTOP_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_VIEW_CATEGORY_DESKTOP_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_VIEW_CATEGORY_DESKTOP_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_VIEW_CATEGORY_MOBILE_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_VIEW_CATEGORY_MOBILE_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_VIEW_CATEGORY_MOBILE_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_VIEW_CATEGORY_TABLET_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_VIEW_CATEGORY_TABLET_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_VIEW_CATEGORY_TABLET_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_APP_INSTALL_DESKTOP_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_APP_INSTALL_DESKTOP_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_APP_INSTALL_DESKTOP_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_APP_INSTALL_MOBILE_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_APP_INSTALL_MOBILE_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_APP_INSTALL_MOBILE_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_APP_INSTALL_TABLET_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_APP_INSTALL_TABLET_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_APP_INSTALL_TABLET_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_UNKNOWN_DESKTOP_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_UNKNOWN_DESKTOP_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_UNKNOWN_DESKTOP_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_UNKNOWN_MOBILE_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_UNKNOWN_MOBILE_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_UNKNOWN_MOBILE_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_UNKNOWN_TABLET_ACTION_TO_DESKTOP_CONVERSION",
    "TOTAL_UNKNOWN_TABLET_ACTION_TO_MOBILE_CONVERSION",
    "TOTAL_UNKNOWN_TABLET_ACTION_TO_TABLET_CONVERSION",
    "TOTAL_PAGE_VISIT",
    "TOTAL_SIGNUP",
    "TOTAL_CHECKOUT",
    "TOTAL_CUSTOM",
    "TOTAL_ADD_TO_CART",
    "TOTAL_LEAD",
    "TOTAL_SEARCH",
    "TOTAL_WATCH_VIDEO",
    "TOTAL_VIEW_CATEGORY",
    "TOTAL_APP_INSTALL",
    "TOTAL_ADD_TO_WISHLIST",
    "TOTAL_SUBSCRIBE",
    "TOTAL_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CUSTOM_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ADD_TO_CART_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_LEAD_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_SEARCH_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WATCH_VIDEO_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_VIEW_CATEGORY_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_APP_INSTALL_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CHECKOUT_QUANTITY",
    "PAGE_VISIT_COST_PER_ACTION",
    "APP_INSTALL_COST_PER_ACTION",
    "PAGE_VISIT_ROAS",
    "CHECKOUT_ROAS",
    "CUSTOM_ROAS",
    "PRODUCT_GROUP_AD_IMAGE_TAG",
    "PRODUCT_GROUP_AD_VIDEO_TAG",
    "VIDEO_3SEC_VIEWS_1",
    "VIDEO_15SEC_UNIQUE_VIEWS_1",
    "VIDEO_P100_COMPLETE_1",
    "VIDEO_P0_COMBINED_1",
    "VIDEO_P25_COMBINED_1",
    "VIDEO_P50_COMBINED_1",
    "VIDEO_P75_COMBINED_1",
    "VIDEO_P95_COMBINED_1",
    "VIDEO_MRC_VIEWS_1",
    "VIDEO_3SEC_VIEWS_2",
    "VIDEO_15SEC_UNIQUE_VIEWS_2",
    "VIDEO_P100_COMPLETE_2",
    "VIDEO_P0_COMBINED_2",
    "VIDEO_P25_COMBINED_2",
    "VIDEO_P50_COMBINED_2",
    "VIDEO_P75_COMBINED_2",
    "VIDEO_P95_COMBINED_2",
    "VIDEO_MRC_VIEWS_2",
    "PAID_VIDEO_VIEWABLE_RATE",
    "VIDEO_LENGTH",
    "VIDEO_SPEND_IN_DOLLAR",
    "CPV_IN_MICRO_DOLLAR",
    "ECPV_IN_DOLLAR",
    "CPCV_IN_MICRO_DOLLAR",
    "ECPCV_IN_DOLLAR",
    "CPCV_P95_IN_MICRO_DOLLAR",
    "ECPCV_P95_IN_DOLLAR",
    "TOTAL_VIDEO_3SEC_VIEWS",
    "TOTAL_VIDEO_15SEC_UNIQUE_VIEWS",
    "TOTAL_VIDEO_P100_COMPLETE",
    "TOTAL_VIDEO_P0_COMBINED",
    "TOTAL_VIDEO_P25_COMBINED",
    "TOTAL_VIDEO_P50_COMBINED",
    "TOTAL_VIDEO_P75_COMBINED",
    "TOTAL_VIDEO_P95_COMBINED",
    "TOTAL_VIDEO_MRC_VIEWS",
    "VIDEO_AVG_WATCHTIME_IN_SECOND_1",
    "VIDEO_AVG_WATCHTIME_IN_SECOND_2",
    "TOTAL_VIDEO_AVG_WATCHTIME_IN_SECOND",
    "TOTAL_DESTINATION_VIEWS",
    "TOTAL_REPIN_RATE",
    "WEB_CHECKOUT_COST_PER_ACTION",
    "WEB_CHECKOUT_ROAS",
    "TOTAL_WEB_CHECKOUT",
    "TOTAL_WEB_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_CLICK_CHECKOUT",
    "TOTAL_WEB_CLICK_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_ENGAGEMENT_CHECKOUT",
    "TOTAL_WEB_ENGAGEMENT_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_VIEW_CHECKOUT",
    "TOTAL_WEB_VIEW_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "INAPP_CHECKOUT_COST_PER_ACTION",
    "INAPP_CHECKOUT_ROAS",
    "TOTAL_INAPP_CHECKOUT",
    "TOTAL_INAPP_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_CLICK_CHECKOUT",
    "TOTAL_INAPP_CLICK_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_ENGAGEMENT_CHECKOUT",
    "TOTAL_INAPP_ENGAGEMENT_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_VIEW_CHECKOUT",
    "TOTAL_INAPP_VIEW_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "OFFLINE_CHECKOUT_COST_PER_ACTION",
    "OFFLINE_CHECKOUT_ROAS",
    "TOTAL_OFFLINE_CHECKOUT",
    "TOTAL_OFFLINE_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_CLICK_CHECKOUT",
    "TOTAL_OFFLINE_CLICK_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_ENGAGEMENT_CHECKOUT",
    "TOTAL_OFFLINE_ENGAGEMENT_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_VIEW_CHECKOUT",
    "TOTAL_OFFLINE_VIEW_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "PINTEREST_CHECKOUT_COST_PER_ACTION",
    "PINTEREST_CHECKOUT_ROAS",
    "TOTAL_PINTEREST_CHECKOUT",
    "TOTAL_PINTEREST_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "WEB_ADD_TO_CART_COST_PER_ACTION",
    "WEB_ADD_TO_CART_ROAS",
    "TOTAL_WEB_ADD_TO_CART",
    "TOTAL_WEB_ADD_TO_CART_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_CLICK_ADD_TO_CART",
    "TOTAL_WEB_CLICK_ADD_TO_CART_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_ENGAGEMENT_ADD_TO_CART",
    "TOTAL_WEB_ENGAGEMENT_ADD_TO_CART_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_VIEW_ADD_TO_CART",
    "TOTAL_WEB_VIEW_ADD_TO_CART_VALUE_IN_MICRO_DOLLAR",
    "INAPP_ADD_TO_CART_COST_PER_ACTION",
    "INAPP_ADD_TO_CART_ROAS",
    "TOTAL_INAPP_ADD_TO_CART",
    "TOTAL_INAPP_ADD_TO_CART_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_CLICK_ADD_TO_CART",
    "TOTAL_INAPP_CLICK_ADD_TO_CART_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_ENGAGEMENT_ADD_TO_CART",
    "TOTAL_INAPP_ENGAGEMENT_ADD_TO_CART_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_VIEW_ADD_TO_CART",
    "TOTAL_INAPP_VIEW_ADD_TO_CART_VALUE_IN_MICRO_DOLLAR",
    "WEB_PAGE_VISIT_COST_PER_ACTION",
    "WEB_PAGE_VISIT_ROAS",
    "TOTAL_WEB_PAGE_VISIT",
    "TOTAL_WEB_PAGE_VISIT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_CLICK_PAGE_VISIT",
    "TOTAL_WEB_CLICK_PAGE_VISIT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_ENGAGEMENT_PAGE_VISIT",
    "TOTAL_WEB_ENGAGEMENT_PAGE_VISIT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_VIEW_PAGE_VISIT",
    "TOTAL_WEB_VIEW_PAGE_VISIT_VALUE_IN_MICRO_DOLLAR",
    "WEB_SIGNUP_COST_PER_ACTION",
    "WEB_SIGNUP_ROAS",
    "TOTAL_WEB_SIGNUP",
    "TOTAL_WEB_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_CLICK_SIGNUP",
    "TOTAL_WEB_CLICK_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_ENGAGEMENT_SIGNUP",
    "TOTAL_WEB_ENGAGEMENT_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_VIEW_SIGNUP",
    "TOTAL_WEB_VIEW_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "INAPP_SIGNUP_COST_PER_ACTION",
    "INAPP_SIGNUP_ROAS",
    "TOTAL_INAPP_SIGNUP",
    "TOTAL_INAPP_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_CLICK_SIGNUP",
    "TOTAL_INAPP_CLICK_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_ENGAGEMENT_SIGNUP",
    "TOTAL_INAPP_ENGAGEMENT_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_VIEW_SIGNUP",
    "TOTAL_INAPP_VIEW_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "OFFLINE_SIGNUP_COST_PER_ACTION",
    "OFFLINE_SIGNUP_ROAS",
    "TOTAL_OFFLINE_SIGNUP",
    "TOTAL_OFFLINE_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_CLICK_SIGNUP",
    "TOTAL_OFFLINE_CLICK_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_ENGAGEMENT_SIGNUP",
    "TOTAL_OFFLINE_ENGAGEMENT_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_VIEW_SIGNUP",
    "TOTAL_OFFLINE_VIEW_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "WEB_WATCH_VIDEO_COST_PER_ACTION",
    "WEB_WATCH_VIDEO_ROAS",
    "TOTAL_WEB_WATCH_VIDEO",
    "TOTAL_WEB_WATCH_VIDEO_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_CLICK_WATCH_VIDEO",
    "TOTAL_WEB_CLICK_WATCH_VIDEO_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_ENGAGEMENT_WATCH_VIDEO",
    "TOTAL_WEB_ENGAGEMENT_WATCH_VIDEO_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_VIEW_WATCH_VIDEO",
    "TOTAL_WEB_VIEW_WATCH_VIDEO_VALUE_IN_MICRO_DOLLAR",
    "WEB_LEAD_COST_PER_ACTION",
    "WEB_LEAD_ROAS",
    "TOTAL_WEB_LEAD",
    "TOTAL_WEB_LEAD_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_CLICK_LEAD",
    "TOTAL_WEB_CLICK_LEAD_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_ENGAGEMENT_LEAD",
    "TOTAL_WEB_ENGAGEMENT_LEAD_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_VIEW_LEAD",
    "TOTAL_WEB_VIEW_LEAD_VALUE_IN_MICRO_DOLLAR",
    "OFFLINE_LEAD_COST_PER_ACTION",
    "OFFLINE_LEAD_ROAS",
    "TOTAL_OFFLINE_LEAD",
    "TOTAL_OFFLINE_LEAD_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_CLICK_LEAD",
    "TOTAL_OFFLINE_CLICK_LEAD_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_ENGAGEMENT_LEAD",
    "TOTAL_OFFLINE_ENGAGEMENT_LEAD_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_VIEW_LEAD",
    "TOTAL_OFFLINE_VIEW_LEAD_VALUE_IN_MICRO_DOLLAR",
    "WEB_SEARCH_COST_PER_ACTION",
    "WEB_SEARCH_ROAS",
    "TOTAL_WEB_SEARCH",
    "TOTAL_WEB_SEARCH_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_CLICK_SEARCH",
    "TOTAL_WEB_CLICK_SEARCH_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_ENGAGEMENT_SEARCH",
    "TOTAL_WEB_ENGAGEMENT_SEARCH_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_VIEW_SEARCH",
    "TOTAL_WEB_VIEW_SEARCH_VALUE_IN_MICRO_DOLLAR",
    "INAPP_SEARCH_COST_PER_ACTION",
    "INAPP_SEARCH_ROAS",
    "TOTAL_INAPP_SEARCH",
    "TOTAL_INAPP_SEARCH_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_CLICK_SEARCH",
    "TOTAL_INAPP_CLICK_SEARCH_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_ENGAGEMENT_SEARCH",
    "TOTAL_INAPP_ENGAGEMENT_SEARCH_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_VIEW_SEARCH",
    "TOTAL_INAPP_VIEW_SEARCH_VALUE_IN_MICRO_DOLLAR",
    "WEB_VIEW_CATEGORY_COST_PER_ACTION",
    "WEB_VIEW_CATEGORY_ROAS",
    "TOTAL_WEB_VIEW_CATEGORY",
    "TOTAL_WEB_VIEW_CATEGORY_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_CLICK_VIEW_CATEGORY",
    "TOTAL_WEB_CLICK_VIEW_CATEGORY_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_ENGAGEMENT_VIEW_CATEGORY",
    "TOTAL_WEB_ENGAGEMENT_VIEW_CATEGORY_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_VIEW_VIEW_CATEGORY",
    "TOTAL_WEB_VIEW_VIEW_CATEGORY_VALUE_IN_MICRO_DOLLAR",
    "WEB_CUSTOM_COST_PER_ACTION",
    "WEB_CUSTOM_ROAS",
    "TOTAL_WEB_CUSTOM",
    "TOTAL_WEB_CUSTOM_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_CLICK_CUSTOM",
    "TOTAL_WEB_CLICK_CUSTOM_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_ENGAGEMENT_CUSTOM",
    "TOTAL_WEB_ENGAGEMENT_CUSTOM_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_VIEW_CUSTOM",
    "TOTAL_WEB_VIEW_CUSTOM_VALUE_IN_MICRO_DOLLAR",
    "OFFLINE_CUSTOM_COST_PER_ACTION",
    "OFFLINE_CUSTOM_ROAS",
    "TOTAL_OFFLINE_CUSTOM",
    "TOTAL_OFFLINE_CUSTOM_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_CLICK_CUSTOM",
    "TOTAL_OFFLINE_CLICK_CUSTOM_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_ENGAGEMENT_CUSTOM",
    "TOTAL_OFFLINE_ENGAGEMENT_CUSTOM_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_VIEW_CUSTOM",
    "TOTAL_OFFLINE_VIEW_CUSTOM_VALUE_IN_MICRO_DOLLAR",
    "WEB_UNKNOWN_COST_PER_ACTION",
    "WEB_UNKNOWN_ROAS",
    "TOTAL_WEB_UNKNOWN",
    "TOTAL_WEB_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_CLICK_UNKNOWN",
    "TOTAL_WEB_CLICK_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_ENGAGEMENT_UNKNOWN",
    "TOTAL_WEB_ENGAGEMENT_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_VIEW_UNKNOWN",
    "TOTAL_WEB_VIEW_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "INAPP_UNKNOWN_COST_PER_ACTION",
    "INAPP_UNKNOWN_ROAS",
    "TOTAL_INAPP_UNKNOWN",
    "TOTAL_INAPP_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_CLICK_UNKNOWN",
    "TOTAL_INAPP_CLICK_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_ENGAGEMENT_UNKNOWN",
    "TOTAL_INAPP_ENGAGEMENT_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_VIEW_UNKNOWN",
    "TOTAL_INAPP_VIEW_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "OFFLINE_UNKNOWN_COST_PER_ACTION",
    "OFFLINE_UNKNOWN_ROAS",
    "TOTAL_OFFLINE_UNKNOWN",
    "TOTAL_OFFLINE_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_CLICK_UNKNOWN",
    "TOTAL_OFFLINE_CLICK_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_ENGAGEMENT_UNKNOWN",
    "TOTAL_OFFLINE_ENGAGEMENT_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_OFFLINE_VIEW_UNKNOWN",
    "TOTAL_OFFLINE_VIEW_UNKNOWN_VALUE_IN_MICRO_DOLLAR",
    "INAPP_APP_INSTALL_COST_PER_ACTION",
    "INAPP_APP_INSTALL_ROAS",
    "TOTAL_INAPP_APP_INSTALL",
    "TOTAL_INAPP_APP_INSTALL_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_CLICK_APP_INSTALL",
    "TOTAL_INAPP_CLICK_APP_INSTALL_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_ENGAGEMENT_APP_INSTALL",
    "TOTAL_INAPP_ENGAGEMENT_APP_INSTALL_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_INAPP_VIEW_APP_INSTALL",
    "TOTAL_INAPP_VIEW_APP_INSTALL_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_APP_INSTALL_CONVERSION_RATE",
    "TOTAL_INAPP_APP_INSTALL_CONVERSION_RATE",
    "IDEA_PIN_PAGE_FORWARD_1",
    "IDEA_PIN_PAGE_FORWARD_2",
    "IDEA_PIN_PAGE_BACKWARD_1",
    "IDEA_PIN_PAGE_BACKWARD_2",
    "TOTAL_IDEA_PIN_PAGE_FORWARD",
    "TOTAL_IDEA_PIN_PAGE_BACKWARD",
    "IDEA_PIN_PRODUCT_TAG_VISIT_1",
    "IDEA_PIN_PRODUCT_TAG_VISIT_2",
    "TOTAL_IDEA_PIN_PRODUCT_TAG_VISIT",
    "LEADS",
    "COST_PER_LEAD",
    "QUIZ_COMPLETED",
    "QUIZ_COMPLETION_RATE",
    "SHOWCASE_PIN_CLICKTHROUGH",
    "SHOWCASE_SUBPAGE_CLICKTHROUGH",
    "SHOWCASE_SUBPIN_CLICKTHROUGH",
    "SHOWCASE_SUBPAGE_IMPRESSION",
    "SHOWCASE_SUBPIN_IMPRESSION",
    "SHOWCASE_SUBPAGE_SWIPE_LEFT",
    "SHOWCASE_SUBPAGE_SWIPE_RIGHT",
    "SHOWCASE_SUBPIN_SWIPE_LEFT",
    "SHOWCASE_SUBPIN_SWIPE_RIGHT",
    "SHOWCASE_SUBPAGE_REPIN",
    "SHOWCASE_SUBPIN_REPIN",
    "SHOWCASE_SUBPAGE_CLOSEUP",
    "SHOWCASE_CARD_THUMBNAIL_SWIPE_FORWARD",
    "SHOWCASE_CARD_THUMBNAIL_SWIPE_BACKWARD",
    "SHOWCASE_AVERAGE_SUBPAGE_CLOSEUP_PER_SESSION",
    "TOTAL_CHECKOUT_CONVERSION_RATE",
    "TOTAL_VIEW_CATEGORY_CONVERSION_RATE",
    "TOTAL_ADD_TO_CART_CONVERSION_RATE",
    "TOTAL_SIGNUP_CONVERSION_RATE",
    "TOTAL_PAGE_VISIT_CONVERSION_RATE",
    "TOTAL_LEAD_CONVERSION_RATE",
    "TOTAL_SEARCH_CONVERSION_RATE",
    "TOTAL_WATCH_VIDEO_CONVERSION_RATE",
    "TOTAL_UNKNOWN_CONVERSION_RATE",
    "TOTAL_CUSTOM_CONVERSION_RATE",
    "STANDARD_AD_FEED_ITEM_ID",
    "SPEND_ORDER_LINE_ID",
    "INAPP_SKAN_APP_INSTALL",
    "INAPP_SKAN_ASSISTED_APP_INSTALL",
    "INAPP_SKAN_APP_INSTALL_COST_PER_ACTION",
    "INAPP_SKAN_APP_INSTALL_CONVERSION_RATE",
)

EXPECTED_ASYNC_COUNT = 626

# The single sync-only column (ReportingColumnSync minus ReportingColumnAsync).
SYNC_ONLY: tuple[str, ...] = ("QUIZ_PIN_RESULT_OPEN",)

EXPECTED_UNION_COUNT = 627  # 626 async + 1 sync-only (the official column space)

# ---------------------------------------------------------------------------
# 2. SYNC_ALSO -- the 184 async columns also in ReportingColumnSync (Annex A
#    [S] markers). ReportingColumnSync = these 184 + QUIZ_PIN_RESULT_OPEN.
# ---------------------------------------------------------------------------
SYNC_ALSO: frozenset[str] = frozenset((
    "ADVERTISER_ID",
    "AD_ACCOUNT_ID",
    "AD_GROUP_BID_MULTIPLIER",
    "AD_GROUP_BUDGET_IN_LOCAL_CURRENCY",
    "AD_GROUP_BUDGET_TYPE",
    "AD_GROUP_ENTITY_STATUS",
    "AD_GROUP_ID",
    "AD_GROUP_NAME",
    "AD_GROUP_OPTIMIZATION",
    "AD_ID",
    "AD_NAME",
    "CAMPAIGN_BRAND_LABEL",
    "CAMPAIGN_BUDGET_OPTIMIZATION",
    "CAMPAIGN_DAILY_SPEND_CAP",
    "CAMPAIGN_ENTITY_STATUS",
    "CAMPAIGN_ID",
    "CAMPAIGN_LIFETIME_SPEND_CAP",
    "CAMPAIGN_NAME",
    "CAMPAIGN_OBJECTIVE_TYPE",
    "CHECKOUT_ROAS",
    "CLICKTHROUGH_1",
    "CLICKTHROUGH_1_GROSS",
    "CLICKTHROUGH_2",
    "COLLECTION_PIN_ITEM_CLICKTHROUGH_1",
    "COLLECTION_PIN_ITEM_CLICKTHROUGH_2",
    "COLLECTION_PIN_ITEM_IMPRESSION_1",
    "COLLECTION_PIN_ITEM_IMPRESSION_2",
    "COST_PER_LEAD",
    "COST_PER_OUTBOUND_CLICK_IN_DOLLAR",
    "COST_PER_OUTBOUND_CLICK_IN_DOLLAR_1",
    "CPC_IN_MICRO_DOLLAR",
    "CPM_IN_DOLLAR",
    "CPM_IN_MICRO_DOLLAR",
    "CTR",
    "CTR_2",
    "CUSTOM_ROAS",
    "ECPCV_IN_DOLLAR",
    "ECPCV_P95_IN_DOLLAR",
    "ECPC_IN_DOLLAR",
    "ECPC_IN_MICRO_DOLLAR",
    "ECPE_IN_DOLLAR",
    "ECPM_IN_MICRO_DOLLAR",
    "ECPV_IN_DOLLAR",
    "ECTR",
    "EENGAGEMENT_RATE",
    "ENGAGEMENT_1",
    "ENGAGEMENT_2",
    "ENGAGEMENT_RATE",
    "IDEA_PIN_PRODUCT_TAG_VISIT_1",
    "IDEA_PIN_PRODUCT_TAG_VISIT_2",
    "IMPRESSION_1",
    "IMPRESSION_1_GROSS",
    "IMPRESSION_2",
    "INAPP_CHECKOUT_COST_PER_ACTION",
    "INAPP_SKAN_APP_INSTALL",
    "INAPP_SKAN_APP_INSTALL_CONVERSION_RATE",
    "INAPP_SKAN_APP_INSTALL_COST_PER_ACTION",
    "INAPP_SKAN_ASSISTED_APP_INSTALL",
    "IS_PREMIERE_CAMPAIGN",
    "LEADS",
    "ORDER_LINE_ID",
    "ORDER_LINE_NAME",
    "OUTBOUND_CLICK_1",
    "OUTBOUND_CLICK_2",
    "OUTBOUND_CTR_1",
    "PAGE_VISIT_COST_PER_ACTION",
    "PAGE_VISIT_ROAS",
    "PAID_IMPRESSION",
    "PAID_VIDEO_VIEWABLE_RATE",
    "PIN_ID",
    "PIN_PROMOTION_ID",
    "PRODUCT_GROUP_AD_IMAGE_TAG",
    "PRODUCT_GROUP_AD_VIDEO_TAG",
    "PROMO_ID",
    "PROMO_NAME",
    "QUIZ_COMPLETED",
    "QUIZ_COMPLETION_RATE",
    "REPIN_1",
    "REPIN_2",
    "REPIN_RATE",
    "SHOWCASE_AVERAGE_SUBPAGE_CLOSEUP_PER_SESSION",
    "SHOWCASE_CARD_THUMBNAIL_SWIPE_BACKWARD",
    "SHOWCASE_CARD_THUMBNAIL_SWIPE_FORWARD",
    "SHOWCASE_PIN_CLICKTHROUGH",
    "SHOWCASE_SUBPAGE_CLICKTHROUGH",
    "SHOWCASE_SUBPAGE_CLOSEUP",
    "SHOWCASE_SUBPAGE_IMPRESSION",
    "SHOWCASE_SUBPAGE_REPIN",
    "SHOWCASE_SUBPAGE_SWIPE_LEFT",
    "SHOWCASE_SUBPAGE_SWIPE_RIGHT",
    "SHOWCASE_SUBPIN_CLICKTHROUGH",
    "SHOWCASE_SUBPIN_IMPRESSION",
    "SHOWCASE_SUBPIN_REPIN",
    "SHOWCASE_SUBPIN_SWIPE_LEFT",
    "SHOWCASE_SUBPIN_SWIPE_RIGHT",
    "SPEND_IN_DOLLAR",
    "SPEND_IN_MICRO_DOLLAR",
    "TOTAL_ADD_TO_CART_CONVERSION_RATE",
    "TOTAL_ADD_TO_WISHLIST",
    "TOTAL_APP_INSTALL_CONVERSION_RATE",
    "TOTAL_CHECKOUT",
    "TOTAL_CHECKOUT_CONVERSION_RATE",
    "TOTAL_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CLICKTHROUGH",
    "TOTAL_CLICK_ADD_TO_CART",
    "TOTAL_CLICK_CHECKOUT",
    "TOTAL_CLICK_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_CLICK_LEAD",
    "TOTAL_CLICK_SIGNUP",
    "TOTAL_CLICK_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_COLLECTION_PIN_ITEM_CLICKTHROUGH",
    "TOTAL_COLLECTION_PIN_ITEM_IMPRESSION",
    "TOTAL_CONVERSIONS",
    "TOTAL_CUSTOM",
    "TOTAL_CUSTOM_CONVERSION_RATE",
    "TOTAL_CUSTOM_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ENGAGEMENT",
    "TOTAL_ENGAGEMENT_CHECKOUT",
    "TOTAL_ENGAGEMENT_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_ENGAGEMENT_LEAD",
    "TOTAL_ENGAGEMENT_SIGNUP",
    "TOTAL_ENGAGEMENT_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_IDEA_PIN_PRODUCT_TAG_VISIT",
    "TOTAL_IMPRESSION",
    "TOTAL_IMPRESSION_FREQUENCY",
    "TOTAL_IMPRESSION_USER",
    "TOTAL_INAPP_APP_INSTALL_CONVERSION_RATE",
    "TOTAL_LEAD",
    "TOTAL_LEAD_CONVERSION_RATE",
    "TOTAL_OFFLINE_CHECKOUT",
    "TOTAL_PAGE_VISIT",
    "TOTAL_PAGE_VISIT_CONVERSION_RATE",
    "TOTAL_REPIN_RATE",
    "TOTAL_SEARCH_CONVERSION_RATE",
    "TOTAL_SIGNUP",
    "TOTAL_SIGNUP_CONVERSION_RATE",
    "TOTAL_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_SUBSCRIBE",
    "TOTAL_UNKNOWN_CONVERSION_RATE",
    "TOTAL_VIDEO_15SEC_UNIQUE_VIEWS",
    "TOTAL_VIDEO_3SEC_VIEWS",
    "TOTAL_VIDEO_AVG_WATCHTIME_IN_SECOND",
    "TOTAL_VIDEO_MRC_VIEWS",
    "TOTAL_VIDEO_P0_COMBINED",
    "TOTAL_VIDEO_P100_COMPLETE",
    "TOTAL_VIDEO_P25_COMBINED",
    "TOTAL_VIDEO_P50_COMBINED",
    "TOTAL_VIDEO_P75_COMBINED",
    "TOTAL_VIDEO_P95_COMBINED",
    "TOTAL_VIEW_ADD_TO_CART",
    "TOTAL_VIEW_CATEGORY_CONVERSION_RATE",
    "TOTAL_VIEW_CHECKOUT",
    "TOTAL_VIEW_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_VIEW_LEAD",
    "TOTAL_VIEW_SIGNUP",
    "TOTAL_VIEW_SIGNUP_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WATCH_VIDEO_CONVERSION_RATE",
    "TOTAL_WEB_CHECKOUT",
    "TOTAL_WEB_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_CLICK_CHECKOUT",
    "TOTAL_WEB_CLICK_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_ENGAGEMENT_CHECKOUT",
    "TOTAL_WEB_ENGAGEMENT_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "TOTAL_WEB_SESSIONS",
    "TOTAL_WEB_VIEW_CHECKOUT",
    "TOTAL_WEB_VIEW_CHECKOUT_VALUE_IN_MICRO_DOLLAR",
    "VIDEO_15SEC_UNIQUE_VIEWS_1",
    "VIDEO_15SEC_UNIQUE_VIEWS_2",
    "VIDEO_3SEC_VIEWS_1",
    "VIDEO_3SEC_VIEWS_2",
    "VIDEO_LENGTH",
    "VIDEO_MRC_VIEWS_1",
    "VIDEO_MRC_VIEWS_2",
    "VIDEO_P0_COMBINED_2",
    "VIDEO_P100_COMPLETE_2",
    "VIDEO_P25_COMBINED_2",
    "VIDEO_P50_COMBINED_2",
    "VIDEO_P75_COMBINED_2",
    "VIDEO_P95_COMBINED_2",
    "VIDEO_SPEND_IN_DOLLAR",
    "WEB_CHECKOUT_COST_PER_ACTION",
    "WEB_CHECKOUT_ROAS",
    "WEB_SESSIONS_1",
    "WEB_SESSIONS_2",
))

EXPECTED_SYNC_ALSO_COUNT = 184

# ---------------------------------------------------------------------------
# 3. DIMENSIONS -- the 53 entity-attribute columns (Annex A [dim] markers).
#    Everything else in the enum is a metric.
# ---------------------------------------------------------------------------
DIMENSIONS: frozenset[str] = frozenset((
    "ADVERTISER_ID",
    "AD_ACCOUNT_ID",
    "AD_GROUP_BID_MULTIPLIER",
    "AD_GROUP_BUDGET_IN_LOCAL_CURRENCY",
    "AD_GROUP_BUDGET_TYPE",
    "AD_GROUP_ENTITY_STATUS",
    "AD_GROUP_ID",
    "AD_GROUP_NAME",
    "AD_GROUP_OPTIMIZATION",
    "AD_GROUP_STATUS",
    "AD_ID",
    "AD_NAME",
    "AD_STATUS",
    "CAMPAIGN",
    "CAMPAIGN_BRAND_LABEL",
    "CAMPAIGN_BUDGET_OPTIMIZATION",
    "CAMPAIGN_CUSTOM_LABELS",
    "CAMPAIGN_DAILY_SPEND_CAP",
    "CAMPAIGN_ENTITY_STATUS",
    "CAMPAIGN_ID",
    "CAMPAIGN_LIFETIME_SPEND_CAP",
    "CAMPAIGN_MANAGED_STATUS",
    "CAMPAIGN_NAME",
    "CAMPAIGN_OBJECTIVE_TYPE",
    "CAMPAIGN_STATUS",
    "IS_CATALOG_CREATIVE_CAMPAIGN",
    "IS_PREMIERE_CAMPAIGN",
    "ORDER_LINE_ID",
    "ORDER_LINE_NAME",
    "PIN_ID",
    "PIN_PROMOTION_ID",
    "PIN_PROMOTION_NAME",
    "PIN_PROMOTION_STATUS",
    "PRODUCT_GROUP_AD_IMAGE_TAG",
    "PRODUCT_GROUP_AD_VIDEO_TAG",
    "PRODUCT_GROUP_ID",
    "PRODUCT_GROUP_STATUS",
    "PRODUCT_ITEM_BRAND",
    "PRODUCT_ITEM_CURRENCY",
    "PRODUCT_ITEM_DESCRIPTION",
    "PRODUCT_ITEM_IMAGE_URL",
    "PRODUCT_ITEM_NAME",
    "PRODUCT_ITEM_PIN_URL",
    "PRODUCT_ITEM_PRICE",
    "PRODUCT_ITEM_PRODUCT_CATEGORY",
    "PRODUCT_ITEM_PRODUCT_TYPE",
    "PRODUCT_ITEM_PRODUCT_URL",
    "PRODUCT_ITEM_SALE_PRICE",
    "PROMO_ID",
    "PROMO_NAME",
    "SPEND_ORDER_LINE_ID",
    "STANDARD_AD_FEED_ITEM_ID",
    "VIDEO_LENGTH",
))

EXPECTED_DIMENSION_COUNT = 53

# ---------------------------------------------------------------------------
# DESCRIPTIVE_MUTABLE (Story 26.6 Part A) -- entity STATE/TYPE dimensions whose
# value MUTATES over time for a fixed grain key (a campaign paused, an ad group
# objective retargeted). They are attributes of the entity, NOT row-bearing
# breakdowns: two different values for the SAME (date, entity) are the SAME
# fact restated, latest-wins -- never two rows to keep.
#
# The refetch ladder (26.1) re-pulls historical windows nightly; without this
# marking a status flip between two pulls would produce a NEW segments_json and
# the stale row would survive the QUALIFY supersede, DOUBLING every metric of
# the re-pulled window. So the CONNECTOR lands these OUT of segments_json (the
# grain key) into a SEPARATE attributes_json column (hors partition, latest-
# wins), exactly as campaign_name already behaves.
#
# Prudent default (story contract): a dimension carrying an entity STATUS /
# ENTITY_STATUS / MANAGED_STATUS, or an OBJECTIVE_TYPE / BUDGET_TYPE, is
# descriptive_mutable. What is DELIBERATELY EXCLUDED and stays in the grain:
#   - grain-bearing ids (CAMPAIGN_ID, AD_GROUP_ID, AD_ID, PIN_ID,
#     PRODUCT_GROUP_ID, ORDER_LINE_ID...) -- they DEFINE the row;
#   - the 99 CONVERSION DEVICE PATH metrics and every conversion-family metric
#     -- they are VALUES, not entity attributes (never here);
#   - names (CAMPAIGN_NAME...) already land latest-wins outside segments_json
#     via the structural columns, so they are not re-listed here.
# A dimension NOT in this set keeps the conservative catalog behaviour (grain).
DESCRIPTIVE_MUTABLE: frozenset[str] = frozenset((
    # Campaign state / type / objective.
    "CAMPAIGN_STATUS",
    "CAMPAIGN_ENTITY_STATUS",
    "CAMPAIGN_MANAGED_STATUS",
    "CAMPAIGN_OBJECTIVE_TYPE",
    "CAMPAIGN_BUDGET_OPTIMIZATION",
    # Ad group state / type.
    "AD_GROUP_STATUS",
    "AD_GROUP_ENTITY_STATUS",
    "AD_GROUP_BUDGET_TYPE",
    "AD_GROUP_OPTIMIZATION",
    # Ad / pin-promotion state.
    "AD_STATUS",
    "PIN_PROMOTION_STATUS",
    # Product group state.
    "PRODUCT_GROUP_STATUS",
))

EXPECTED_DESCRIPTIVE_MUTABLE_COUNT = 12

# ---------------------------------------------------------------------------
# Dimension ownership by report level (drives the field_compatibility rules
# AND the ENTITY/PRODUCT ITEM section split). Sources: async report response
# attributes per level (OpenAPI 5.28.0) + the PRODUCT_ITEM restriction ("pin
# promotion / ad columns forbidden at level PRODUCT_ITEM").
# ---------------------------------------------------------------------------
ACCOUNT_DIMS = frozenset((
    "ADVERTISER_ID", "AD_ACCOUNT_ID", "ORDER_LINE_ID", "ORDER_LINE_NAME",
    "SPEND_ORDER_LINE_ID", "PROMO_ID", "PROMO_NAME",
))
CAMPAIGN_DIMS = frozenset((
    "CAMPAIGN", "CAMPAIGN_ID", "CAMPAIGN_NAME", "CAMPAIGN_STATUS",
    "CAMPAIGN_ENTITY_STATUS", "CAMPAIGN_MANAGED_STATUS",
    "CAMPAIGN_OBJECTIVE_TYPE", "CAMPAIGN_BRAND_LABEL", "CAMPAIGN_CUSTOM_LABELS",
    "CAMPAIGN_DAILY_SPEND_CAP", "CAMPAIGN_LIFETIME_SPEND_CAP",
    "CAMPAIGN_BUDGET_OPTIMIZATION", "IS_CATALOG_CREATIVE_CAMPAIGN",
    "IS_PREMIERE_CAMPAIGN",
))
AD_GROUP_DIMS = frozenset((
    "AD_GROUP_ID", "AD_GROUP_NAME", "AD_GROUP_STATUS", "AD_GROUP_ENTITY_STATUS",
    "AD_GROUP_BUDGET_TYPE", "AD_GROUP_BUDGET_IN_LOCAL_CURRENCY",
    "AD_GROUP_BID_MULTIPLIER", "AD_GROUP_OPTIMIZATION",
))
AD_DIMS = frozenset((
    "AD_ID", "AD_NAME", "AD_STATUS", "PIN_ID", "PIN_PROMOTION_ID",
    "PIN_PROMOTION_NAME", "PIN_PROMOTION_STATUS", "STANDARD_AD_FEED_ITEM_ID",
    "VIDEO_LENGTH",
))
PRODUCT_GROUP_DIMS = frozenset((
    "PRODUCT_GROUP_ID", "PRODUCT_GROUP_STATUS",
    "PRODUCT_GROUP_AD_IMAGE_TAG", "PRODUCT_GROUP_AD_VIDEO_TAG",
))
PRODUCT_ITEM_DIMS = frozenset((
    "PRODUCT_ITEM_NAME", "PRODUCT_ITEM_IMAGE_URL", "PRODUCT_ITEM_PRICE",
    "PRODUCT_ITEM_PRODUCT_URL", "PRODUCT_ITEM_PIN_URL", "PRODUCT_ITEM_BRAND",
    "PRODUCT_ITEM_DESCRIPTION", "PRODUCT_ITEM_SALE_PRICE",
    "PRODUCT_ITEM_PRODUCT_TYPE", "PRODUCT_ITEM_PRODUCT_CATEGORY",
    "PRODUCT_ITEM_CURRENCY",
))

# The catalog_daily level whitelist (story 26.3) -> allowed dimension families.
# PRODUCT_ITEM and *_TARGETING levels are NOT whitelisted in v1 (dedicated
# window profile / targeting_types parameter -- see catalog_sources.json).
# KEYWORD is NOT whitelisted in v1 either (review 26.3 F-3): the enum carries
# NO observable keyword identity column (no KEYWORD_ID / keyword text), so N
# keywords of an ad group would collapse onto one grain key and the QUALIFY
# supersede would keep one arbitrary row. Ratification at the live probe ONLY
# if the response rows carry an observable identity key (ROLLOUT_NOTES).
LEVEL_DIMS: dict[str, frozenset[str]] = {
    "CAMPAIGN": ACCOUNT_DIMS | CAMPAIGN_DIMS,
    "AD_GROUP": ACCOUNT_DIMS | CAMPAIGN_DIMS | AD_GROUP_DIMS,
    "PIN_PROMOTION": ACCOUNT_DIMS | CAMPAIGN_DIMS | AD_GROUP_DIMS | AD_DIMS,
    "PRODUCT_GROUP": (
        ACCOUNT_DIMS | CAMPAIGN_DIMS | AD_GROUP_DIMS | PRODUCT_GROUP_DIMS
    ),
}


# ---------------------------------------------------------------------------
# Ratio / derived detection (non-additive, AD-4) and physical data_type.
# ---------------------------------------------------------------------------

_RATIO_PREFIXES = ("CPC_", "CPM_", "CPV_", "CPCV_", "ECP", "ECTR", "CTR",
                   "OUTBOUND_CTR", "COST_PER_")
_RATIO_MARKERS = ("_RATE", "ROAS", "_CTR", "FREQUENCY", "AVERAGE", "_AVG_",
                  "COST_PER_ACTION")


def _is_ratio_or_derived(name: str) -> bool:
    """True for provider-computed ratio/derived metrics (never SUM -- AD-4)."""
    if name.startswith(_RATIO_PREFIXES):
        return True
    if name in ("CTR", "CTR_2", "ECTR", "EENGAGEMENT_RATE", "ENGAGEMENT_RATE",
                "REPIN_RATE", "TOTAL_REPIN_RATE", "TOTAL_IMPRESSION_FREQUENCY"):
        return True
    return any(marker in name for marker in _RATIO_MARKERS)


# ---------------------------------------------------------------------------
# Section assignment (ordered, first match wins) -- transposed from the
# research draft _section_note name families.
# ---------------------------------------------------------------------------


def _dimension_section(name: str) -> str:
    if name in PRODUCT_ITEM_DIMS:
        return S_PRODUCT_ITEM
    if name == "VIDEO_LENGTH":
        return S_VIDEO
    return S_ENTITY


def _metric_section(name: str) -> str:
    if "_ACTION_TO_" in name and name.endswith("_CONVERSION"):
        return S_DEVICE_PATH
    if "WEB_SESSION" in name:
        return S_WEB_SESSIONS
    if "COLLECTION_PIN_ITEM" in name:
        return S_COLLECTION
    if name.startswith(("TOTAL_VIDEO_", "VIDEO_")) or name in (
        "ECPV_IN_DOLLAR", "ECPCV_IN_DOLLAR", "ECPCV_P95_IN_DOLLAR",
    ):
        return S_VIDEO
    if _is_ratio_or_derived(name):
        return S_PERFORMANCE
    if name.endswith("_VALUE_IN_MICRO_DOLLAR"):
        return S_CONVERSION_VALUE
    if name.startswith(("SPEND_", "ADS_CREDIT_")):
        return S_SPEND
    if name in ("PAID_IMPRESSION", "TOTAL_IMPRESSION", "TOTAL_IMPRESSION_USER") or (
        name.startswith("IMPRESSION_")
    ):
        return S_IMPRESSION
    if name == "TOTAL_CLICKTHROUGH" or name.startswith(
        ("CLICKTHROUGH_", "OUTBOUND_CLICK_")
    ):
        return S_CLICKTHROUGH
    if name.startswith(("SHOWCASE_", "QUIZ_")) or name in (
        "TOTAL_ENGAGEMENT", "ENGAGEMENT_1", "ENGAGEMENT_2", "REPIN_1", "REPIN_2",
    ):
        return S_ENGAGEMENT
    # Everything left is a conversion-event family count/quantity
    # (TOTAL_<EVENT>*, ONSITE_*, INAPP_*, IDEA_PIN_*, LEADS, ...).
    return S_CONVERSION


_DECIMAL_METRICS = frozenset((
    "TOTAL_VIDEO_AVG_WATCHTIME_IN_SECOND",
))


def _metric_data_type(name: str) -> str:
    if name.endswith("_IN_MICRO_DOLLAR") or "_IN_MICRO_DOLLAR_" in name:
        return "int"  # int64 micro-currency on the wire; landed as value/1e6
    if "_IN_DOLLAR" in name:
        return "currency"
    if _is_ratio_or_derived(name) or name in _DECIMAL_METRICS:
        return "decimal"
    return "int"  # count metrics


_DIM_TYPE_OVERRIDES: dict[str, str] = {
    "CAMPAIGN_DAILY_SPEND_CAP": "int",     # micro-currency cap (int64)
    "CAMPAIGN_LIFETIME_SPEND_CAP": "int",  # micro-currency cap (int64)
    "AD_GROUP_BUDGET_IN_LOCAL_CURRENCY": "currency",
    "AD_GROUP_BID_MULTIPLIER": "decimal",
    "VIDEO_LENGTH": "decimal",
    "IS_CATALOG_CREATIVE_CAMPAIGN": "boolean",
    "IS_PREMIERE_CAMPAIGN": "boolean",
}


def _dimension_data_type(name: str) -> str:
    return _DIM_TYPE_OVERRIDES.get(name, "string")


_MICROS_NOTE = (
    " int64 micro-currency amount on the wire (1e-6 of the ad account"
    " currency); landed as value/1e6 (platform micros rule, story 26.3 --"
    " the connector derives its conversion set from THIS catalog marker,"
    " never from an id-suffix heuristic)."
)
_RATIO_NOTE = (
    " Provider-computed ratio/derived metric: NON-ADDITIVE (AD-4) -- never"
    " SUM across rows; recompute at the semantic layer from stored"
    " numerators and denominators."
)
_MUTABLE_NOTE = (
    " DESCRIPTIVE MUTABLE (story 26.6 Part A): an entity STATE/TYPE attribute"
    " that changes over time for a fixed grain -- landed in attributes_json"
    " (latest-wins), NEVER in the segments_json supersede grain key, so a"
    " refetch that re-reads a window with a changed status does not double the"
    " metrics of that window."
)


def build() -> list[dict]:
    """Return the official snapshot entries (deterministic, sorted)."""
    if len(ASYNC_COLUMNS) != EXPECTED_ASYNC_COUNT:
        raise ValueError(
            f"async enum count drifted: {len(ASYNC_COLUMNS)} != {EXPECTED_ASYNC_COUNT}"
        )
    if len(set(ASYNC_COLUMNS)) != EXPECTED_ASYNC_COUNT:
        raise ValueError("duplicate column in ASYNC_COLUMNS")
    if len(SYNC_ALSO) != EXPECTED_SYNC_ALSO_COUNT:
        raise ValueError(
            f"sync-also count drifted: {len(SYNC_ALSO)} != {EXPECTED_SYNC_ALSO_COUNT}"
        )
    if len(DIMENSIONS) != EXPECTED_DIMENSION_COUNT:
        raise ValueError(
            f"dimension count drifted: {len(DIMENSIONS)} != {EXPECTED_DIMENSION_COUNT}"
        )
    if not SYNC_ALSO <= set(ASYNC_COLUMNS):
        raise ValueError("SYNC_ALSO must be a subset of ASYNC_COLUMNS")
    if not DIMENSIONS <= set(ASYNC_COLUMNS):
        raise ValueError("DIMENSIONS must be a subset of ASYNC_COLUMNS")
    if len(DESCRIPTIVE_MUTABLE) != EXPECTED_DESCRIPTIVE_MUTABLE_COUNT:
        raise ValueError(
            f"descriptive_mutable count drifted: {len(DESCRIPTIVE_MUTABLE)} != "
            f"{EXPECTED_DESCRIPTIVE_MUTABLE_COUNT}"
        )
    # Every descriptive_mutable field MUST be a declared dimension (a metric can
    # never be an entity attribute) and MUST NOT be a grain-bearing id.
    if not DESCRIPTIVE_MUTABLE <= DIMENSIONS:
        raise ValueError(
            "DESCRIPTIVE_MUTABLE must be a subset of DIMENSIONS: "
            f"{sorted(DESCRIPTIVE_MUTABLE - DIMENSIONS)}"
        )
    if any(name.endswith("_ID") for name in DESCRIPTIVE_MUTABLE):
        raise ValueError(
            "a grain-bearing *_ID must never be descriptive_mutable: "
            f"{sorted(n for n in DESCRIPTIVE_MUTABLE if n.endswith('_ID'))}"
        )

    out: list[dict] = []

    def add(field_id, kind, data_type, section, description, source_field,
            descriptive_mutable=False):
        entry = {
            "field_id": field_id,
            "kind": kind,
            "data_type": data_type,
            "description": description,
            "section": section,
            "source_field": source_field,
        }
        if descriptive_mutable:
            # Story 26.6 Part A: landed in attributes_json (latest-wins), NEVER
            # in the segments_json supersede grain key.
            entry["descriptive_mutable"] = True
        out.append(entry)

    for name in ASYNC_COLUMNS:
        is_dim = name in DIMENSIONS
        kind = "dimension" if is_dim else "metric"
        reach = (
            "Requestable via the async report path AND the sync analytics"
            " endpoints (ReportingColumnSync member)."
            if name in SYNC_ALSO
            else "Requestable via the async report path only"
            " (POST /ad_accounts/{id}/reports; not in ReportingColumnSync)."
        )
        desc = (
            f"Pinterest Ads reporting column '{name}'"
            " (ReportingColumnAsync, OpenAPI 5.28.0). " + reach
        )
        is_mutable = name in DESCRIPTIVE_MUTABLE
        if is_dim:
            desc += " Entity attribute (dimension) of the report row."
            data_type = _dimension_data_type(name)
            section = _dimension_section(name)
            if is_mutable:
                desc += _MUTABLE_NOTE
        else:
            data_type = _metric_data_type(name)
            section = _metric_section(name)
            if data_type == "int" and (
                name.endswith("_IN_MICRO_DOLLAR") or "_IN_MICRO_DOLLAR_" in name
            ):
                desc += _MICROS_NOTE
            if _is_ratio_or_derived(name):
                desc += _RATIO_NOTE
        add(name, kind, data_type, section, desc, name,
            descriptive_mutable=is_mutable)

    # The single sync-only column (union member #627).
    add(
        "QUIZ_PIN_RESULT_OPEN",
        "metric",
        "int",
        S_ENGAGEMENT,
        "Pinterest Ads reporting column 'QUIZ_PIN_RESULT_OPEN'"
        " (ReportingColumnSync, OpenAPI 5.28.0). SYNC-ONLY: the one column of"
        " the sync enum ABSENT from ReportingColumnAsync -- NOT requestable"
        " through the async report path that catalog_daily uses (excluded"
        " with reason in the generated catalog; reachable when a sync-columns"
        " profile lands).",
        "QUIZ_PIN_RESULT_OPEN",
    )

    # The structural grain dimension of the report response (NOT an enum
    # value, never sent in `columns`): granularity DAY stamps a DATE key on
    # every row.
    add(
        "date",
        "dimension",
        "date",
        S_TIME,
        "Reporting day (UTC date, 'DATE' key of the report response row at"
        " granularity DAY). Structural grain dimension -- not a"
        " ReportingColumn enum value; it is never sent in the request's"
        " 'columns' array.",
        "DATE",
    )

    out.sort(key=lambda e: e["field_id"])
    return out


# ---------------------------------------------------------------------------
# field_compatibility (core schema "1") -- one selectable_set rule per
# whitelisted catalog_daily level, regenerated in catalog_sources.json.
# ---------------------------------------------------------------------------


def build_field_compatibility() -> dict:
    metrics = sorted(
        name for name in ASYNC_COLUMNS if name not in DIMENSIONS
    )
    rules = []
    for level in sorted(LEVEL_DIMS):
        allowed = sorted(set(metrics) | LEVEL_DIMS[level] | {"date"})
        rules.append({
            "id": f"level_selectable_{level.lower()}",
            "kind": "selectable_set",
            "scope": {"level": level},
            "allowed_fields": allowed,
            "_note": (
                f"Columns selectable in an async report at level={level}:"
                " every async metric + the entity-attribute dimensions of"
                f" the {level} lineage + the date grain."
                " QUIZ_PIN_RESULT_OPEN (sync-only) and PRODUCT_ITEM_*"
                " attributes are reachable at NO whitelisted level (typed"
                " pre-call refusal)."
            ),
        })
    return {
        "schema_version": "1",
        "_note": (
            "Story 26.3 -- GENERATED by build_official_fields.py (do not edit"
            " by hand; regen keeps the rules in lockstep with the enum)."
            " Core contract (field-compatibility.schema.json, 26.1):"
            " selectable_set rules scoped {'level': <LEVEL>} consumed by"
            " core.field_compat.enforce_selection with"
            " context={'level': ...} BEFORE any API call. Date-window /"
            " granularity limits are request-parameter validation (not field"
            " rules): see _request_limits."
        ),
        "_source": (
            "POST /ad_accounts/{ad_account_id}/reports endpoint description +"
            " per-level response attributes, OpenAPI 5.28.0"
        ),
        "rules": rules,
    }


def build_descriptive_mutable() -> dict:
    """Story 26.6 Part A: the DERIVED descriptive_mutable block for
    catalog_sources.json.

    The connector reads THIS block (not api_catalog.json -- whose core schema
    forbids extra field keys, and which is out-of-scope to change) to decide
    which landed columns leave segments_json for attributes_json. The list is
    the OFFICIAL enum ids; the connector maps them to their canonical landed
    names through the same manifest rename map transform() uses, so a mutable
    attribute is recognised whether it lands under its enum id or its canonical
    name (e.g. CAMPAIGN_ENTITY_STATUS -> campaign_status).
    """
    return {
        "schema_version": "1",
        "_note": (
            "Story 26.6 Part A -- GENERATED by build_official_fields.py (do not"
            " edit by hand). Entity STATE/TYPE dimensions that mutate over time"
            " for a fixed grain: the connector lands them in attributes_json"
            " (latest-wins, HORS partition) instead of segments_json (the"
            " QUALIFY supersede grain key), so a refetch re-reading a window"
            " with a changed status does not double the window's metrics."
            " Grain-bearing ids and conversion/device-path metrics are NEVER"
            " listed here."
        ),
        "field_ids": sorted(DESCRIPTIVE_MUTABLE),
    }


def main() -> None:
    fields = build()
    metrics = sum(1 for f in fields if f["kind"] == "metric")
    dims = sum(1 for f in fields if f["kind"] == "dimension")
    here = Path(__file__).parent

    out_path = here / "official_fields.json"
    out_path.write_text(
        json.dumps(fields, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )

    # Regenerate the field_compatibility + descriptive_mutable blocks in
    # catalog_sources.json (both kept in lockstep with the enum).
    sources_path = here / "catalog_sources.json"
    sources = json.loads(sources_path.read_text(encoding="utf-8"))
    sources["field_compatibility"] = build_field_compatibility()
    sources["descriptive_mutable"] = build_descriptive_mutable()
    sources_path.write_text(
        json.dumps(sources, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )

    print(
        f"Wrote {len(fields)} fields ({metrics} metrics / {dims} dimensions;"
        f" union of the official enums = {EXPECTED_UNION_COUNT} + 1 date grain;"
        f" {len(DESCRIPTIVE_MUTABLE)} descriptive_mutable) to {out_path};"
        f" field_compatibility + descriptive_mutable regenerated in {sources_path}"
    )


if __name__ == "__main__":
    main()
