"""Local dev loop runner — Story 1.4, T5.1.

Executes the full generate -> load -> dbt run -> dbt test pipeline against
the local DuckDB fallback. Exits non-zero on first failure.

Usage:
    # from repo root
    uv run python server/modules/google-analytics/seeds/run_local_loop.py

    # with custom paths
    uv run python server/modules/google-analytics/seeds/run_local_loop.py \\
        --duckdb-path /tmp/my_test.duckdb
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parents[4]  # connector/
SEEDS_DIR = Path(__file__).parent
DBT_DIR = REPO_ROOT / "dbt"


def _run(
    label: str,
    cmd: list[str],
    cwd: Path | None = None,
    env: dict | None = None,
) -> None:
    print(f"\n{'='*60}")
    print(f"STEP: {label}")
    print(f"CMD:  {' '.join(cmd)}")
    print(f"{'='*60}")
    result = subprocess.run(cmd, cwd=str(cwd or REPO_ROOT), env=env)
    if result.returncode != 0:
        print(f"\nFAILED: {label} (exit {result.returncode})")
        sys.exit(result.returncode)
    print(f"OK: {label}")


def _write_local_profiles_yml(profiles_dir: Path, duckdb_path: str) -> None:
    """Write a profiles.yml into dbt/profiles/ pointing at the given DuckDB path.

    This file is gitignored and created fresh each run so the loop is self-contained.
    Calling the loop multiple times is idempotent — the file is overwritten.
    """
    profiles_dir.mkdir(parents=True, exist_ok=True)
    profiles_yml = profiles_dir / "profiles.yml"
    content = f"""# Auto-generated by run_local_loop.py — DO NOT COMMIT (gitignored).
# To regenerate: uv run python server/modules/google-analytics/seeds/run_local_loop.py
connector:
  target: local
  outputs:
    local:
      type: duckdb
      path: {duckdb_path!r}
      threads: 1
"""
    profiles_yml.write_text(content, encoding="utf-8")
    print(f"  Wrote dbt profiles.yml -> {profiles_yml}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the full local seed loop")
    parser.add_argument(
        "--duckdb-path",
        default=str(SEEDS_DIR / "local.duckdb"),
        help="DuckDB file path for the local fallback warehouse",
    )
    parser.add_argument(
        "--csv-path",
        default=str(SEEDS_DIR / "ga4_seed.csv"),
        help="Output path for the generated seed CSV",
    )
    args = parser.parse_args()

    # Ensure dbt profiles.yml exists and points to the chosen DuckDB path
    _write_local_profiles_yml(DBT_DIR / "profiles", args.duckdb_path)

    run_env = {**os.environ, "TOOROW_DUCKDB_PATH": args.duckdb_path}

    # 1 — Generate seed CSV
    _run(
        "Generate seed CSV",
        [
            sys.executable if sys.executable else "python",
            str(SEEDS_DIR / "generate_seed.py"),
            "--out", args.csv_path,
        ],
        env=run_env,
    )

    # 2 — Load into DuckDB
    _run(
        "Load seed -> DuckDB",
        [
            sys.executable if sys.executable else "python",
            str(SEEDS_DIR / "load_seed.py"),
            "--mode", "duckdb",
            "--csv-path", args.csv_path,
            "--duckdb-path", args.duckdb_path,
        ],
        env=run_env,
    )

    # 1b — Generate the GA4 user_type_daily seed CSV (Epic 10, story 10.1).
    user_type_csv = str(SEEDS_DIR / "ga4_user_type_seed.csv")
    _run(
        "Generate user_type seed CSV",
        [
            sys.executable if sys.executable else "python",
            str(SEEDS_DIR / "generate_seed.py"),
            "--profile", "user_type_daily",
            "--out", user_type_csv,
        ],
        env=run_env,
    )

    # 2a2 — Load the GA4 user_type_daily seed into DuckDB (raw_ga4_user_type_daily).
    _run(
        "Load user_type seed -> DuckDB",
        [
            sys.executable if sys.executable else "python",
            str(SEEDS_DIR / "load_seed_user_type.py"),
            "--mode", "duckdb",
            "--csv-path", user_type_csv,
            "--duckdb-path", args.duckdb_path,
        ],
        env=run_env,
    )

    # 1c/2a3 — Generate + load the GA4 pages_daily seeds (Epic 10, story 10.3).
    # TWO profiles (Task 1): landing (sessions by landing_page) + paths
    # (screen_page_views by page), each Zipf-like over ~30 URL paths, top-N bounded.
    landing_csv = str(SEEDS_DIR / "ga4_landing_seed.csv")
    _run(
        "Generate pages landing seed CSV",
        [
            sys.executable if sys.executable else "python",
            str(SEEDS_DIR / "generate_seed.py"),
            "--profile", "pages_daily_landing",
            "--out", landing_csv,
        ],
        env=run_env,
    )
    _run(
        "Load pages landing seed -> DuckDB",
        [
            sys.executable if sys.executable else "python",
            str(SEEDS_DIR / "load_seed_pages.py"),
            "--profile", "landing",
            "--mode", "duckdb",
            "--csv-path", landing_csv,
            "--duckdb-path", args.duckdb_path,
        ],
        env=run_env,
    )
    paths_csv = str(SEEDS_DIR / "ga4_paths_seed.csv")
    _run(
        "Generate pages paths seed CSV",
        [
            sys.executable if sys.executable else "python",
            str(SEEDS_DIR / "generate_seed.py"),
            "--profile", "pages_daily_paths",
            "--out", paths_csv,
        ],
        env=run_env,
    )
    _run(
        "Load pages paths seed -> DuckDB",
        [
            sys.executable if sys.executable else "python",
            str(SEEDS_DIR / "load_seed_pages.py"),
            "--profile", "paths",
            "--mode", "duckdb",
            "--csv-path", paths_csv,
            "--duckdb-path", args.duckdb_path,
        ],
        env=run_env,
    )

    # 1d/2a4 — Generate + load the GA4 acquisition seeds (Epic 16, story 16.1).
    # TWO profiles (Task 1): session (last click: conversions + sessions by
    # session_source_medium x session_campaign) + first_user (first click: conversions
    # by first_user_source_medium), each top-N bounded. Without these, dbt run fails
    # (the mart refs stg_ga4_acquisition_* whose raw sources would not exist).
    acq_session_csv = str(SEEDS_DIR / "ga4_acquisition_session_seed.csv")
    _run(
        "Generate acquisition session seed CSV",
        [
            sys.executable if sys.executable else "python",
            str(SEEDS_DIR / "generate_seed.py"),
            "--profile", "acquisition_session",
            "--out", acq_session_csv,
        ],
        env=run_env,
    )
    _run(
        "Load acquisition session seed -> DuckDB",
        [
            sys.executable if sys.executable else "python",
            str(SEEDS_DIR / "load_seed_acquisition.py"),
            "--profile", "session",
            "--mode", "duckdb",
            "--csv-path", acq_session_csv,
            "--duckdb-path", args.duckdb_path,
        ],
        env=run_env,
    )
    acq_first_user_csv = str(SEEDS_DIR / "ga4_acquisition_first_user_seed.csv")
    _run(
        "Generate acquisition first_user seed CSV",
        [
            sys.executable if sys.executable else "python",
            str(SEEDS_DIR / "generate_seed.py"),
            "--profile", "acquisition_first_user",
            "--out", acq_first_user_csv,
        ],
        env=run_env,
    )
    _run(
        "Load acquisition first_user seed -> DuckDB",
        [
            sys.executable if sys.executable else "python",
            str(SEEDS_DIR / "load_seed_acquisition.py"),
            "--profile", "first_user",
            "--mode", "duckdb",
            "--csv-path", acq_first_user_csv,
            "--duckdb-path", args.duckdb_path,
        ],
        env=run_env,
    )

    # 2b — Load Meta Ads seed rows (Story 3.6) so the module-owned staging model
    # has a source table and fact_daily_kpi proves the second-source join
    # (connector='meta-ads' rows appear alongside GA4). The Meta seed loader lives
    # in the meta-ads module (AD-2: module owns its own seed/staging).
    meta_seed = (
        REPO_ROOT / "server" / "modules" / "meta-ads" / "seeds" / "load_meta_seed.py"
    )
    _run(
        "Load Meta Ads seed -> DuckDB",
        [
            sys.executable if sys.executable else "python",
            str(meta_seed),
            "--duckdb-path", args.duckdb_path,
        ],
        env=run_env,
    )

    # 2c — Load GSC seed rows (Story 6.2) so the module-owned staging model
    # has a source table and fact_daily_kpi proves the third-source join
    # (connector='gsc' rows appear alongside GA4 and Meta Ads). The GSC seed loader
    # lives in the gsc module (AD-2: module owns its own seed/staging).
    gsc_seed = (
        REPO_ROOT / "server" / "modules" / "gsc" / "seeds" / "load_gsc_seed.py"
    )
    _run(
        "Load GSC seed -> DuckDB",
        [
            sys.executable if sys.executable else "python",
            str(gsc_seed),
            "--duckdb-path", args.duckdb_path,
        ],
        env=run_env,
    )

    # 2b — dbt seed (declarative configs, e.g. metric_source_priority — Story 3.7)
    # Story 4.1: --project-dir required so dbt resolves seed-paths relative to dbt_project.yml
    # location (not the Python cwd). This avoids "dbt\seeds\..." path confusion on Windows.
    _run(
        "dbt seed",
        [sys.executable, "-m", "dbt.cli.main", "seed",
         "--project-dir", str(DBT_DIR), "--profiles-dir", str(DBT_DIR / "profiles")],
        cwd=REPO_ROOT,
        env=run_env,
    )

    # 3 — dbt run
    _run(
        "dbt run",
        [sys.executable, "-m", "dbt.cli.main", "run",
         "--project-dir", str(DBT_DIR), "--profiles-dir", str(DBT_DIR / "profiles")],
        cwd=REPO_ROOT,
        env=run_env,
    )

    # 4 — dbt test
    _run(
        "dbt test",
        [sys.executable, "-m", "dbt.cli.main", "test",
         "--project-dir", str(DBT_DIR), "--profiles-dir", str(DBT_DIR / "profiles")],
        cwd=REPO_ROOT,
        env=run_env,
    )

    print("\n" + "="*60)
    print("LOCAL LOOP COMPLETE — all steps passed.")
    print(f"Warehouse: {args.duckdb_path}")
    print("="*60)


if __name__ == "__main__":
    main()
