/* GENERATED by scripts/generate-build-info.mjs -- do not edit.
 * Regenerate with `pnpm --filter @toorow/card-shell generate:build-identity`,
 * which also re-emits src/viz/rendererBuilds.generated.json: the two carry ONE
 * identity and are never regenerated apart.
 * The hash covers src/viz/** (see scripts/runtime-identity.mjs), so it moves
 * only when the runtime moves. */
export const RUNTIME_SEMVER = "0.1.0";
export const RUNTIME_CONTENT_HASH = "87c254baf75d";
