"""Un notebook : le lister, le lire, le changer, le lancer, le planifier, l exporter.

AD-43, 2026-08-13. Sept routes et un sujet. La huitieme adresse du prefixe,
`/share`, est servie par `render_shares_api.share_notebook_gone` -- une porte
retiree qui dit son retrait plutot que de disparaitre, et elle reste montee
depuis son module d origine.
"""

from __future__ import annotations

import html as html_module
import json
import logging

from starlette.requests import Request
from starlette.responses import JSONResponse, Response
from starlette.routing import Route

from core.audit import (
    ACTION_CROSS_SCOPE_ATTEMPT,
    declare_action,
    write_audit_row,
)

logger = logging.getLogger("core.admin_api")

# --- le joint qui reste dans admin_api -----------------------------------
async def _check_auth(*args, **kwargs):
    """Le joint d'`admin_api`, atteint a l'APPEL -- jamais capture a l'import."""
    from core.admin_api import _check_auth as _impl  # noqa: PLC0415
    return await _impl(*args, **kwargs)

def _project_not_found_response(*args, **kwargs):
    """Le joint d'`admin_api`, atteint a l'APPEL -- jamais capture a l'import."""
    from core.admin_api import _project_not_found_response as _impl  # noqa: PLC0415
    return _impl(*args, **kwargs)

def _strict_project_capability_allowed(*args, **kwargs):
    """Le joint d'`admin_api`, atteint a l'APPEL -- jamais capture a l'import."""
    from core.admin_api import _strict_project_capability_allowed as _impl  # noqa: PLC0415
    return _impl(*args, **kwargs)

# --- les handlers, deplaces TELS QUELS -----------------------------------

ACTION_NOTEBOOK_DELETED = declare_action("notebook_deleted")

_HTML_SLIDE_TEMPLATE = """\
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title} — {executed_at}</title>
  <style>
    /* Print-friendly standalone HTML — no external references (AD-11) */
    *, *::before, *::after {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      padding: 2rem;
      background: #ffffff;
      color: #1a1a1a;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;
      font-size: 15px;
      line-height: 1.6;
      max-width: 900px;
      margin-left: auto;
      margin-right: auto;
    }}
    h1 {{ font-size: 1.75rem; margin: 0 0 0.5rem; font-weight: 700; color: #111; }}
    .meta {{
      font-size: 0.85rem; color: #666; margin-bottom: 1.5rem;
      border-bottom: 1px solid #e0e0e0; padding-bottom: 0.75rem;
    }}
    .narrative {{
      white-space: pre-wrap; background: #f9f9f9;
      border: 1px solid #e0e0e0; border-radius: 4px;
      padding: 1rem; font-size: 0.95rem;
    }}
    .data-table {{ width: 100%; border-collapse: collapse; margin-top: 1.5rem; }}
    .data-table th, .data-table td {{
      border: 1px solid #ddd; padding: 0.5rem 0.75rem;
      text-align: left; font-size: 0.875rem;
    }}
    .data-table th {{ background: #f5f5f5; font-weight: 600; }}
    .data-table tr:nth-child(even) td {{ background: #fafafa; }}
    .footer {{
      margin-top: 2rem; font-size: 0.75rem; color: #999;
      border-top: 1px solid #e0e0e0; padding-top: 0.5rem;
    }}
    @media print {{
      body {{ padding: 1rem; font-size: 13px; }}
      .narrative {{ border: none; background: transparent; padding: 0; }}
    }}
  </style>
</head>
<body>
  <h1>{title}</h1>
  <p class="meta">{window_rule} &middot; {executed_at} &middot; Data as of {data_date}</p>
  <pre class="narrative">{summary_text}</pre>
{data_table}
  <div class="footer">Generated by toorow &middot; {executed_at}</div>
</body>
</html>
"""

_TS_COLS_NB = {"created_at", "updated_at", "executed_at", "last_run_at"}

async def _list_notebooks(request: Request) -> Response:
    """GET /api/notebooks?project_id=<id> -- list notebooks for project.

    Response (200):
        [{"id", "title", "report_ref", "window_rule", "created_at",
          "last_run_at" (nullable), "last_run_status" (nullable)}]

    Error responses:
        400 -- missing project_id
        401 -- unauthorized
        500 -- DB error
    """
    authorized, identity = await _check_auth(request)
    if not authorized:
        return JSONResponse(
            {"code": "unauthorized", "message": "Bearer token required"},
            status_code=401,
        )

    project_id = request.query_params.get("project_id") or ""
    if not project_id:
        return JSONResponse(
            {"code": "missing_param", "message": "project_id is required"},
            status_code=400,
        )

    try:
        from core.db import get_connection  # noqa: PLC0415

        with get_connection() as conn:
            allowed = _strict_project_capability_allowed(
                conn,
                identity=identity,
                project_id=project_id,
                minimum_capability="view",
            )
    except Exception as exc:
        logger.warning(
            "admin_api: notebook-list access unavailable project=%s: %s",
            project_id,
            type(exc).__name__,
        )
        return _project_not_found_response()
    if not allowed:
        return _project_not_found_response()

    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT
                        n.id,
                        n.title,
                        n.report_ref,
                        n.window_rule,
                        n.created_at,
                        lr.executed_at  AS last_run_at,
                        lr.status       AS last_run_status
                    FROM app.notebooks n
                    LEFT JOIN LATERAL (
                        SELECT executed_at, status
                        FROM app.notebook_runs
                        WHERE notebook_id = n.id
                        ORDER BY executed_at DESC
                        LIMIT 1
                    ) lr ON true
                    WHERE n.project_id = %s
                    ORDER BY n.created_at DESC
                    """,
                    (project_id,),
                )
                cols = [d[0] for d in cur.description]
                notebooks = []
                for row in cur.fetchall():
                    record: dict = {}
                    for col, val in zip(cols, row):
                        if col in _TS_COLS_NB and val is not None:
                            record[col] = val.isoformat()
                        else:
                            record[col] = val
                    notebooks.append(record)
    except Exception as exc:
        logger.error("admin_api: list_notebooks_error: %s", exc)
        return JSONResponse(
            {"code": "db_error", "message": "Notebooks are temporarily unavailable"},
            status_code=500,
        )

    return JSONResponse(notebooks)

#: LE MAGASIN HERITE EST EN LECTURE SEULE DEPUIS LE 2026-08-22 (story 67.23).
#:
#: `app.notebooks` avait un seul ecrivain -- l'outil MCP `save_notebook` ; il
#: n'existe aucune route REST de creation -- et les ecrans canoniques d'Analyze
#: ne le lisent pas : ils lisent `app.analysis_notebooks` et ses versions. Un
#: modele creait donc un objet reel, audite, que rien ne montrait. La porte MCP
#: a bascule sur le magasin gouverne dans le meme commit ; ces trois ecritures
#: sont l'autre moitie de l'acte, et les laisser ouvertes aurait garde vivant un
#: produit sans createur ni lecteur.
#:
#: ELLES REFUSENT PLUTOT QUE DE DISPARAITRE. Retirer les routes ferait repondre
#: 404 a une ecriture, ce qui dit a l'appelant que son objet n'existe pas et
#: l'envoie le chercher. Le refus nomme le geste qui marche. Les LECTURES
#: restent : `list_legacy_notebooks` tient AC12 << remain readable >>, sur ses
#: zero lignes.
_LEGACY_WRITE_REFUSED = {
    "code": "legacy_store_is_read_only",
    "message": (
        "This Notebook store no longer takes writes. A Notebook is composed, "
        "scheduled and retired in Analyze, on the Project's own Notebooks "
        "surface, which is where every screen reads them from."
    ),
}


def _refuse_legacy_write() -> Response:
    """Le meme refus pour les trois portes -- une seule phrase, un seul code."""
    return JSONResponse(_LEGACY_WRITE_REFUSED, status_code=409)


async def _run_notebook_endpoint(request: Request) -> Response:
    """POST /api/notebooks/{notebook_id}/run -- trigger a notebook run (Story 6.5, AC5, T6.5).

    Calls run_notebook logic server-side (not via MCP protocol layer) and returns
    the new run id. This is the REST trigger for the admin console "Exécuter" button.

    Response (200):
        {"run_id": "nbrun_...", "summary": "...", "pull_ids": [...]}

    Error responses:
        401 -- unauthorized
        404 -- notebook not found
        500 -- run error
    """
    authorized, _identity = await _check_auth(request)
    if not authorized:
        return JSONResponse(
            {"code": "unauthorized", "message": "Bearer token required"},
            status_code=401,
        )

    notebook_id = request.path_params.get("notebook_id", "")

    try:
        body_bytes = await request.body()
        body: dict = json.loads(body_bytes) if body_bytes.strip() else {}
    except Exception:
        body = {}

    as_of = body.get("as_of", "")

    try:
        from core.main import run_notebook  # noqa: PLC0415

        result = run_notebook(notebook_id=notebook_id, as_of=as_of or "")
    except Exception as exc:
        err_str = str(exc)
        # Check if it's a ToolError with code=not_found
        try:
            err_data = json.loads(exc.args[0]) if exc.args else {}
        except Exception:
            err_data = {}
        if err_data.get("code") == "not_found":
            return JSONResponse(
                {"code": "not_found", "message": "Notebook not found"},
                status_code=404,
            )
        logger.error("admin_api: run_notebook_endpoint_error: %s", exc)
        return JSONResponse(
            {"code": "run_error", "message": f"Notebook run failed: {err_str}"},
            status_code=500,
        )

    # Extract run_id from structured_content meta
    sc = result.structured_content or {}
    run_id = sc.get("meta", {}).get("run_id", "")
    pull_ids = sc.get("meta", {}).get("provenance", {}).get("pull_ids", [])
    summary = result.content[0].text if result.content else ""

    return JSONResponse(
        {"run_id": run_id, "summary": summary, "pull_ids": pull_ids},
        status_code=200,
    )

async def _schedule_notebook(request: Request) -> Response:
    """PATCH /api/notebooks/{notebook_id}/schedule -- REFUSE, lecture seule.

    Programmer un Notebook se fait sur la surface Notebooks du Projet, qui ecrit
    `app.analysis_notebook_schedules` et que `dispatch_due_notebook_schedules`
    tire chaque nuit. Cette porte-ci ecrivait `app.notebooks.scheduled`, lu par
    une boucle nocturne retiree le meme jour.
    """
    return _refuse_legacy_write()


async def _export_notebook_html(request: Request) -> Response:
    """GET /api/notebooks/{notebook_id}/runs/{run_id}/export/html -- slide export (Story 6.6, AC5).

    Server-side HTML template rendered from stored envelope_inline + summary_text.
    No LLM call; pure template substitution. No external references (AD-11).

    Response: text/html with inline CSS. Print to PDF from browser.
    """
    authorized, identity = await _check_auth(request)
    if not authorized:
        return JSONResponse(
            {"code": "unauthorized", "message": "Bearer token required"},
            status_code=401,
        )

    notebook_id = request.path_params.get("notebook_id", "")
    run_id = request.path_params.get("run_id", "")
    # Story 7.4 (AC7, AI-38): explicit scope claim from the query string.
    scope_hint = (request.query_params.get("project_id") or "").strip()

    try:
        from core.db import get_connection  # noqa: PLC0415

        with get_connection() as conn:
            with conn.cursor() as cur:
                # Fetch notebook (incl. project_id for scope enforcement)
                cur.execute(
                    "SELECT title, window_rule, project_id FROM app.notebooks WHERE id = %s",
                    (notebook_id,),
                )
                nb_row = cur.fetchone()
                if nb_row is None:
                    return JSONResponse(
                        {"code": "not_found", "message": "Notebook not found"},
                        status_code=404,
                    )
                nb_title, nb_window_rule, nb_project_id = nb_row

                # Story 7.4 (AC7, AI-38): cross-scope EXPORT must 404 (+ audit).
                denied = _enforce_notebook_project_scope(
                    nb_project_id,
                    identity,
                    notebook_id,
                    conn,
                    scope_hint=scope_hint,
                    action="notebook_export",
                )
                if denied is not None:
                    return denied

                # Fetch run
                cur.execute(
                    """
                    SELECT executed_at, summary_text, envelope_inline, pull_ids
                    FROM app.notebook_runs
                    WHERE id = %s AND notebook_id = %s
                    """,
                    (run_id, notebook_id),
                )
                run_row = cur.fetchone()
                if run_row is None:
                    return JSONResponse(
                        {"code": "not_found", "message": "Run not found"},
                        status_code=404,
                    )
                executed_at, summary_text, envelope_inline_raw, pull_ids = run_row
    except Exception as exc:
        logger.error("admin_api: export_notebook_html_error: %s", exc)
        return JSONResponse(
            {"code": "db_error", "message": f"Database error: {exc}"},
            status_code=500,
        )

    # Parse envelope_inline JSONB
    envelope_inline: dict | None = None
    if envelope_inline_raw is not None:
        try:
            envelope_inline = (
                json.loads(envelope_inline_raw)
                if isinstance(envelope_inline_raw, str)
                else envelope_inline_raw
            )
        except Exception:
            envelope_inline = None

    # Determine data_date from first pull_id or envelope
    data_date = "—"
    if envelope_inline:
        prov = envelope_inline.get("meta", {}).get("provenance", {})
        dr = envelope_inline.get("data", {}).get("date_range", {})
        if dr.get("end"):
            data_date = dr["end"]
        elif prov.get("pull_ids"):
            data_date = str(prov["pull_ids"][0])
    elif pull_ids:
        data_date = str(pull_ids[0])

    executed_at_str = executed_at.strftime("%Y-%m-%d %H:%M UTC") if executed_at else "—"
    # Escape HTML in summary

    summary_escaped = html_module.escape(summary_text or "")
    title_escaped = html_module.escape(nb_title or "")
    window_escaped = html_module.escape(nb_window_rule or "")
    data_date_escaped = html_module.escape(data_date)
    data_table_html = _build_data_table_html(envelope_inline)

    html_content = _HTML_SLIDE_TEMPLATE.format(
        title=title_escaped,
        executed_at=executed_at_str,
        window_rule=window_escaped,
        data_date=data_date_escaped,
        summary_text=summary_escaped,
        data_table=data_table_html,
    )

    return Response(
        content=html_content,
        media_type="text/html; charset=utf-8",
        headers={
            # review-epic-6 F-3: belt-and-braces — even if an escape is ever
            # missed, no script/external resource can execute or load.
            "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'",
        },
    )

async def _get_notebook(request: Request) -> Response:
    """GET /api/notebooks/{notebook_id} -- single notebook with last 5 runs.

    Response (200):
        {"id", "title", "report_ref", "window_rule", "narrative_prompt",
         "created_at", "updated_at", "project_id",
         "runs": [{"run_id", "executed_at", "status", "pull_ids"}]}

    Error responses:
        401 -- unauthorized
        404 -- not found or project mismatch
        500 -- DB error
    """
    authorized, identity = await _check_auth(request)
    if not authorized:
        return JSONResponse(
            {"code": "unauthorized", "message": "Bearer token required"},
            status_code=401,
        )

    notebook_id = request.path_params.get("notebook_id", "")
    # project_id for scoping (optional query param; if provided we enforce it)
    filter_project = (request.query_params.get("project_id") or "").strip()

    try:
        from core.db import get_connection  # noqa: PLC0415

        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT id, project_id, title, report_ref, window_rule,
                           narrative_prompt, created_at, updated_at
                    FROM app.notebooks
                    WHERE id = %s
                    """,
                    (notebook_id,),
                )
                row = cur.fetchone()
                if row is None:
                    return JSONResponse(
                        {"code": "not_found", "message": "Notebook not found"},
                        status_code=404,
                    )
                cols = [d[0] for d in cur.description]
                nb: dict = {}
                for col, val in zip(cols, row):
                    if col in _TS_COLS_NB and val is not None:
                        nb[col] = val.isoformat()
                    else:
                        nb[col] = val

                # Story 7.4 (AC4, AI-38): enforce project scope (explicit claim
                # mismatch OR non-member) -> 404 + audit row.
                denied = _enforce_notebook_project_scope(
                    nb["project_id"],
                    identity,
                    notebook_id,
                    conn,
                    scope_hint=filter_project,
                    action="notebook_get",
                )
                if denied is not None:
                    return denied

                # Fetch last 5 runs
                cur.execute(
                    """
                    SELECT id, executed_at, status, pull_ids
                    FROM app.notebook_runs
                    WHERE notebook_id = %s
                    ORDER BY executed_at DESC
                    LIMIT 5
                    """,
                    (notebook_id,),
                )
                runs = []
                for run_row in cur.fetchall():
                    run_id, executed_at, status, pull_ids = run_row
                    runs.append(
                        {
                            "run_id": run_id,
                            "executed_at": executed_at.isoformat() if executed_at else None,
                            "status": status,
                            "pull_ids": pull_ids[:3] if pull_ids else [],
                        }
                    )
                nb["runs"] = runs
    except Exception as exc:
        logger.error("admin_api: get_notebook_error: %s", exc)
        return JSONResponse(
            {"code": "db_error", "message": f"Database error: {exc}"},
            status_code=500,
        )

    return JSONResponse(nb)

async def _patch_notebook(request: Request) -> Response:
    """PATCH /api/notebooks/{notebook_id} -- REFUSE, lecture seule.

    Un Notebook gouverne ne se modifie pas en place : chaque changement APPEND
    une version, et toutes les precedentes restent lisibles. Un PATCH sur le
    magasin herite ecrasait, ce qui rendait inexplicable une narration deja
    batie sur l'etat d'avant.
    """
    return _refuse_legacy_write()


async def _delete_notebook(request: Request) -> Response:
    """DELETE /api/notebooks/{notebook_id} -- REFUSE, lecture seule.

    Retirer un Notebook gouverne est un ARCHIVAGE (`archive_notebook`) : la ligne
    reste, ses versions restent, et un Run deja publie garde de quoi s'expliquer.
    Ce DELETE detruisait la ligne.
    """
    return _refuse_legacy_write()


def _build_data_table_html(envelope_inline: dict | None) -> str:
    """Build an HTML table from the envelope's metrics dict."""
    if not envelope_inline:
        return ""
    data = envelope_inline.get("data", {})
    metrics: dict = data.get("metrics", {})
    if not metrics:
        rows_data: list = data.get("rows", [])
        if not rows_data:
            return ""
        # Build from first 20 rows
        cols = list(rows_data[0].keys()) if rows_data else []
        if not cols:
            return ""
        # review-epic-6 F-3: every stored value is UNTRUSTED — escape it.
        header_cells = "".join(f"<th>{html_module.escape(str(col))}</th>" for col in cols[:8])
        row_html_parts = []
        for r in rows_data[:20]:
            cells = "".join(f"<td>{html_module.escape(str(r.get(c, '')))}</td>" for c in cols[:8])
            row_html_parts.append(f"<tr>{cells}</tr>")
        rows_html = "\n".join(row_html_parts)
        return (
            f'  <table class="data-table"><thead><tr>{header_cells}</tr></thead>'
            f"<tbody>{rows_html}</tbody></table>"
        )
    # Metrics dict: display as metric/value pairs
    header = "<th>Metric</th><th>Value</th>"
    metric_rows = []
    for k, v in list(metrics.items())[:30]:
        metric_rows.append(
            f"<tr><td>{html_module.escape(str(k))}</td><td>{html_module.escape(str(v))}</td></tr>"
        )
    rows_html = "\n".join(metric_rows)
    return (
        f'  <table class="data-table"><thead><tr>{header}</tr></thead>'
        f"<tbody>{rows_html}</tbody></table>"
    )

def _enforce_notebook_project_scope(
    notebook_project_id: str,
    identity: str,
    notebook_id: str,
    conn,
    scope_hint: str = "",
    action: str = "",
) -> Response | None:
    """Return a 404 Response if the caller may not touch this notebook, else None.

    Args:
        notebook_project_id: The notebook's owning project_id (already fetched).
        identity:            Caller subject from the verified Bearer token.
        notebook_id:         The notebook id (for the audit metadata).
        conn:                Open psycopg connection (reused; no new connection).
        scope_hint:          Explicit project_id the caller CLAIMS to be acting
                             within (from ?project_id= or body["project_id"]).
                             Empty = no explicit claim; ACL still applies.
        action:              Human label of the attempted operation (audit meta).

    A refusal ALWAYS writes an ACTION_CROSS_SCOPE_ATTEMPT audit row before
    returning the 404. Returns None (access granted) otherwise.
    """
    denied = False
    reason = ""

    # 1. Explicit scope claim mismatch -> refuse (caller claims a project that is
    #    not the notebook's owner).
    if scope_hint and scope_hint != notebook_project_id:
        denied = True
        reason = "scope_mismatch"
    # 2. Per-identity ACL, through THE SAME DOOR `_list_notebooks` uses.
    #
    #    This step called `project_access.identity_can_read_project` directly,
    #    and that is a second door: `_strict_project_capability_allowed` keeps
    #    the auth-disabled anonymous developer branch that `admin_api` declares
    #    ("Restoring the single door restores both"), and the direct call does
    #    not. So `make dev` LISTED a notebook through this module's own list
    #    route and then answered 404 when the same identity opened it -- one
    #    module, one resource, two answers. Every per-notebook route (get,
    #    patch, delete, run, schedule, export) passes through here, so the
    #    disagreement covered all six.
    elif not _strict_project_capability_allowed(
        conn,
        identity=identity,
        project_id=notebook_project_id,
        minimum_capability="view",
    ):
        denied = True
        reason = "not_a_member"

    if not denied:
        return None

    # Audit the refused access (best-effort; never blocks the 404).
    write_audit_row(
        identity=identity or "anonymous",
        action=ACTION_CROSS_SCOPE_ATTEMPT,
        provider_account="",
        connection_ref="",
        metadata={
            "notebook_id": notebook_id,
            "notebook_project_id": notebook_project_id,
            "claimed_project_id": scope_hint or None,
            "reason": reason,
            "operation": action or "notebook_access",
        },
    )
    logger.warning(
        "admin_api: cross_scope_attempt identity=%s notebook=%s owner_project=%s "
        "claimed=%s reason=%s op=%s",
        identity,
        notebook_id,
        notebook_project_id,
        scope_hint or "-",
        reason,
        action or "-",
    )
    # 404 (not 403): do not disclose that the notebook exists to a non-member.
    return JSONResponse(
        {"code": "not_found", "message": "Notebook not found"},
        status_code=404,
    )


# --- LES ROUTES, dans l'ordre exact ou elles etaient declarees ------------
#
# Starlette resout dans l'ordre de declaration ; chaque collection est epissee
# a la position que ses routes occupaient. La preuve est un dump avant/apres.

NOTEBOOKS_ROUTES_1 = [
    # Story 6.5 (AC5): notebooks CRUD + run trigger.
    # IMPORTANT: the static /api/notebooks route (list) must precede the
    # parametrized routes so Starlette does not absorb the list GET as a notebook_id.
    # The /run endpoint must precede the bare /{notebook_id} routes to avoid
    # Starlette absorbing "run" as a notebook_id path param.
    # Story 6.6: /shared/{token} MUST precede /{notebook_id}/... routes (no auth).
    Route("/api/notebooks", endpoint=_list_notebooks, methods=["GET"]),
    # Story 6.6 (AC3): public shared endpoint -- no auth guard; token is unguessable.
    # MUST be declared before parametrized notebook_id routes to avoid "shared"
    # being absorbed as a notebook_id.
    Route(
        "/api/notebooks/{notebook_id}/run",
        endpoint=_run_notebook_endpoint,
        methods=["POST"],
    ),
    # Story 6.6 (AC2): schedule toggle.
    Route(
        "/api/notebooks/{notebook_id}/schedule",
        endpoint=_schedule_notebook,
        methods=["PATCH"],
    ),
]

NOTEBOOKS_ROUTES_2 = [
    # Story 6.6 (AC5): slide/HTML export.
    Route(
        "/api/notebooks/{notebook_id}/runs/{run_id}/export/html",
        endpoint=_export_notebook_html,
        methods=["GET"],
    ),
    Route(
        "/api/notebooks/{notebook_id}",
        endpoint=_get_notebook,
        methods=["GET"],
    ),
    Route(
        "/api/notebooks/{notebook_id}",
        endpoint=_patch_notebook,
        methods=["PATCH"],
    ),
    Route(
        "/api/notebooks/{notebook_id}",
        endpoint=_delete_notebook,
        methods=["DELETE"],
    ),
]
