#!/usr/bin/env python3
"""Generate the Tailwind `@theme` block from the design tokens.

    python scripts/generate_theme_css.py

`ui/tokens/tokens.json` is the single source of the visual scale. Hand-writing
the `@theme` block would create a second copy that drifts silently — which is
exactly what happened to `ui/tokens/dist/theme.ts`, whose header claims it is
generated while it is maintained by hand.

Run this after any token change. The output file is generated: do not edit it.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "ui" / "tokens" / "tokens.json"
OUTPUT = ROOT / "ui" / "admin" / "src" / "styles" / "theme.css"

# Token path prefix -> Tailwind namespace. Tailwind 4 derives its utilities from
# the namespace, so `--color-accent` yields `text-accent`, `bg-accent`, and so on.
NAMESPACES = {
    "accent": "color",
    "neutral": "color",
    "semantic": "color",
    "viz": "color",
    "shape-radius": "radius",
    "spacing": "spacing",
    "shadow": "shadow",
    "typography-font-family": "font",
}


def flatten(node: dict, prefix: str = "") -> dict[str, str]:
    flat: dict[str, str] = {}
    for key, value in node.items():
        if not isinstance(value, dict):
            continue
        path = f"{prefix}-{key}" if prefix else key
        if "$value" in value:
            flat[path] = str(value["$value"])
        else:
            flat.update(flatten(value, path))
    return flat


def namespace_for(path: str) -> tuple[str, str] | None:
    for prefix, namespace in NAMESPACES.items():
        if path == prefix or path.startswith(f"{prefix}-"):
            name = path[len(prefix):].lstrip("-") or path
            return namespace, name
    return None


def main() -> int:
    tokens = flatten(json.loads(TOKENS.read_text(encoding="utf-8"))["origin"])

    lines = [
        "/* GENERATED by scripts/generate_theme_css.py from ui/tokens/tokens.json.",
        " * Do not edit: change the tokens and regenerate.",
        " */",
        # The cascade order, and it has to come BEFORE the import: a layer first
        # named afterwards is appended AFTER `utilities`, which is the opposite
        # of what is wanted. `legacy` sits between `base` and `components`, so
        # Tailwind utilities beat the 60 unmigrated stylesheets while those
        # sheets still beat Tailwind's preflight.
        "@layer theme, base, legacy, components, utilities;",
        '@import "tailwindcss";',
        # Tailwind 4 replaces the `tailwindcss-animate` plugin with a stylesheet;
        # shadcn components rely on its enter/exit animations.
        '@import "tw-animate-css";',
        '@custom-variant dark (&:where(.dark, .dark *));',
        "",
        "@theme {",
    ]

    grouped: dict[str, list[str]] = {}
    for path, value in sorted(tokens.items()):
        mapped = namespace_for(path)
        if not mapped:
            continue
        namespace, name = mapped
        # A token with no suffix is the namespace default: Tailwind reads
        # `--radius` for `rounded`, not `--radius-shape-radius`.
        variable = f"--{namespace}" if name == path else f"--{namespace}-{name}"
        grouped.setdefault(namespace, []).append(f"  {variable}: {value};")

    for namespace in ("color", "font", "radius", "spacing", "shadow"):
        if namespace in grouped:
            lines.append(f"  /* {namespace} */")
            lines.extend(grouped[namespace])
            lines.append("")

    lines.append("  /* type scale */")
    for path, value in sorted(tokens.items()):
        if path.startswith("typography-") and not path.startswith("typography-font-family"):
            name = path[len("typography-"):]
            if name.endswith("-size"):
                lines.append(f"  --text-{name[:-5]}: {value};")
            elif name.endswith("-weight"):
                lines.append(f"  --font-weight-{name[:-7]}: {value};")
            else:
                lines.append(f"  --{name}: {value};")

    # The shadcn components in src/components/ui/ are real source, and they name
    # their surfaces in their own vocabulary. Mapping those names onto our
    # tokens here is what keeps ONE palette: `bg-primary` inside a shadcn file
    # resolves to the same rose as `bg-primary` in ours. The alternative — the
    # CLI's own `:root` block — would be a second colour system, which is the
    # defect this whole migration exists to remove.
    lines.extend([
        "",
        "  /* shadcn surface names, mapped onto the tokens above */",
        "  --color-background: var(--color-background-light);",
        "  --color-foreground: var(--color-text);",
        "  --color-card: var(--color-surface-light);",
        "  --color-card-foreground: var(--color-text);",
        "  --color-popover: var(--color-surface-light);",
        "  --color-popover-foreground: var(--color-text);",
        "  --color-primary-foreground: var(--color-on-primary);",
        "  --color-secondary: var(--color-background-light);",
        "  --color-secondary-foreground: var(--color-text);",
        "  --color-muted: var(--color-background-light);",
        "  --color-muted-foreground: var(--color-text-secondary);",
        "  --color-accent: var(--color-background-light);",
        "  --color-accent-foreground: var(--color-text);",
        "  --color-destructive: var(--color-error);",
        "  --color-border: var(--color-divider-base);",
        "  --color-input: var(--color-divider-base);",
        "  --color-ring: var(--color-focus);",
        # The shell has used #d1c4e9 as the focus ring since the v3 mockups; it
        # is the decorative purple, and it had no name in the token file.
        "  --color-focus: var(--color-decorative-purple);",
    ])

    # Same technique, applied to the scale. The installed components write
    # `rounded-md`, `text-sm`, `rounded-sm` — names from Tailwind's built-in
    # scale, which our token file does not define, so 110 geometry values were
    # silently resolving to generic defaults instead of the product's own.
    # Naming them here corrects them all at once; editing 110 call sites would
    # have to be redone at every `shadcn add`.
    lines.extend([
        "",
        "  /* shadcn scale names, mapped onto the tokens above */",
        # The ladder is the one measured on the validated v3/v4 mockups:
        # 6 (marks) · 10 (short interactive rows) · 12 (fields) · 14 (menus) ·
        # 16 (cards, dialogs) · 999 (buttons, chips).
        "  --radius-sm: var(--radius-small);",   # 6px  — marks, checkbox
        "  --radius-md: var(--radius-control);", # 10px — menu items, icon buttons
        "  --radius-lg: var(--radius);",         # 12px — fields, selectors
        "  --radius-xl: var(--radius-large);",   # 16px — cards, dialogs
        # shadcn writes `text-sm` on table cells, menu rows, select items and
        # tabs. The mockups set all four at 14px, not at the 15px prose size,
        # so `text-sm` is the UI size and `text-body` stays prose.
        "  --text-xs: var(--text-caption);",     # 12px
        "  --text-sm: var(--text-ui);",          # 14px
        "  --text-base: var(--text-h3);",        # 16px
        "  --shadow-xs: var(--shadow-card-light);",
        "  --shadow-sm: var(--shadow-card-light);",
        "  --shadow-md: var(--shadow-overlay);",
        "  --shadow-lg: var(--shadow-overlay);",
    ])

    # Radix measures the panel and exposes its height as a variable; the
    # keyframes have to read it, so they cannot come from a generic animation
    # library. Declared inside @theme so `animate-collapsible-down` exists as a
    # utility rather than as a class written per screen.
    lines.extend([
        "",
        "  /* collapsible, driven by the height Radix measures */",
        "  --animate-collapsible-down: collapsible-down 180ms ease-out;",
        "  --animate-collapsible-up: collapsible-up 180ms ease-out;",
        "",
        "  @keyframes collapsible-down {",
        "    from { height: 0; }",
        "    to { height: var(--radix-collapsible-content-height); }",
        "  }",
        "  @keyframes collapsible-up {",
        "    from { height: var(--radix-collapsible-content-height); }",
        "    to { height: 0; }",
        "  }",
    ])

    # The information arc of a status in flight — motion-iconography.md § Running:
    # "Rotation: 900 ms linear infinite using `transform` only." The pulsing
    # box-shadow written first violated l.78 of that file, which forbids
    # animating shadow blur; only transform and opacity may move.
    lines.extend([
        "",
        "  /* the arc of a status in flight (Status active) */",
        "  --animate-arc: arc 900ms linear infinite;",
        "",
        "  @keyframes arc {",
        "    to { transform: rotate(360deg); }",
        "  }",
    ])

    lines.append("}")
    lines.extend([
        "",
        ":root.dark {",
        "  --color-background-light: var(--color-surface-dark);",
        "  --color-surface-light: var(--color-surface-dark-elevated);",
        "  --color-text: var(--color-text-on-dark);",
        "  --color-text-secondary: color-mix(in srgb, var(--color-text-on-dark) 68%, transparent);",
        "  --color-divider-base: var(--color-divider-medium);",
        "}",
    ])
    lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    emitted = sum(1 for line in lines if line.strip().startswith("--"))
    print(f"  {emitted} tokens -> {OUTPUT.relative_to(ROOT).as_posix()} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
