"""Shopify orders seed generator — Story 15.4 (Epic 15).

Produces ~90 days of realistic Shopify orders for the local dev/CI loop and the
seed->mart integration test. The rows are the CANONICAL raw shape that
connector._parse_order() produces (date, order_id, transaction_id, revenue,
refund_amount, orders_count, revenue_source_currency) so the golden conformance
fixture (AI-54) can be regenerated by the SAME parse logic, not written by hand.

Properties (calibrated to the story ACs):
  * ~90 days, a handful of orders/day with weekday seasonality (weekends lighter).
  * transaction_id present on >= 95% of orders (a small deterministic slice is left
    without one to exercise the nullable path and the >=95% quality gate).
  * a few refunds (refund_amount > 0 on ~8% of orders), stored in a DEDICATED column
    (never subtracted from revenue -- decision de story 15.4).
  * ASCII-only stdout (AI-03).

Usage:
    python generate_shopify_seed.py                 # writes shopify_orders_seed.csv
    python generate_shopify_seed.py --out /tmp/x.csv
"""

from __future__ import annotations

import argparse
import csv
import os
import random
from datetime import date, timedelta
from pathlib import Path

WEEKDAY_MULTIPLIERS: dict[int, float] = {
    0: 1.00,  # Monday
    1: 1.05,  # Tuesday
    2: 1.03,  # Wednesday
    3: 1.02,  # Thursday
    4: 1.10,  # Friday (payday shopping)
    5: 0.80,  # Saturday
    6: 0.70,  # Sunday
}

# Base number of orders on a rank-1.0 weekday (before noise / seasonality).
BASE_ORDERS_PER_DAY = 12
# Average order value band (EUR) and refund behaviour.
AOV_RANGE: tuple[float, float] = (28.0, 220.0)
REFUND_PROBABILITY = 0.08          # ~8% of orders carry a (partial) refund
REFUND_FRACTION_RANGE = (0.2, 1.0)  # partial to full refund of the order value
# Fraction of orders deliberately left WITHOUT a transaction_id (draft/free-like).
# Kept at 3% so overall transaction_id presence stays >= 95% (calibrated for the gate).
NO_TXN_PROBABILITY = 0.03

COLUMNS = [
    "date",
    "order_id",
    "transaction_id",
    "revenue",
    "refund_amount",
    "orders_count",
    "revenue_source_currency",
]


def generate_rows(
    days: int = 90,
    end_date: date | None = None,
    *,
    rng: random.Random | None = None,
    currency: str = "EUR",
) -> list[dict]:
    """Return deterministic canonical Shopify raw order rows for the last *days* days.

    Rows match connector._parse_order() output shape exactly (AI-54 fixture honesty):
    the golden conformance fixture is a SLICE of these rows and its expected_facts are
    produced by connector.transform() over the same rows.
    """
    if end_date is None:
        end_date = date.today()
    if rng is None:
        # Fixed seed -> deterministic seed data (reproducible fixtures/tests).
        rng = random.Random(15_4_2026)

    start_date = end_date - timedelta(days=days)
    order_seq = 1000000000
    rows: list[dict] = []

    for offset in range(days):
        day = start_date + timedelta(days=offset)
        multiplier = WEEKDAY_MULTIPLIERS[day.weekday()]
        n_orders = max(1, round(BASE_ORDERS_PER_DAY * multiplier * rng.uniform(0.8, 1.2)))

        for _ in range(n_orders):
            order_seq += 1
            order_id = str(order_seq)
            revenue = round(rng.uniform(*AOV_RANGE), 2)

            refund_amount = 0.0
            if rng.random() < REFUND_PROBABILITY:
                frac = rng.uniform(*REFUND_FRACTION_RANGE)
                refund_amount = round(revenue * frac, 2)

            # transaction_id present on ~97% of orders (>= 95% gate).
            if rng.random() < NO_TXN_PROBABILITY:
                transaction_id = None
            else:
                # Shopify transaction ids are large integers; derive deterministically.
                transaction_id = str(order_seq * 7 + 3)

            rows.append(
                {
                    "date": day.isoformat(),
                    "order_id": order_id,
                    "transaction_id": transaction_id,
                    "revenue": revenue,
                    "refund_amount": refund_amount,
                    "orders_count": 1,
                    "revenue_source_currency": currency,
                }
            )
    return rows


def write_csv(rows: list[dict], path: str | os.PathLike) -> None:
    """Write rows to *path* as a CSV with header (transaction_id blank when None)."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=COLUMNS)
        writer.writeheader()
        for r in rows:
            row = dict(r)
            if row.get("transaction_id") is None:
                row["transaction_id"] = ""
            writer.writerow(row)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Shopify orders seed CSV")
    parser.add_argument("--out", default=None, help="Output CSV path (defaults next to this file)")
    parser.add_argument("--days", type=int, default=90, help="Number of days to seed")
    args = parser.parse_args()

    here = Path(__file__).parent
    out = args.out or str(here / "shopify_orders_seed.csv")
    rows = generate_rows(days=args.days)
    write_csv(rows, out)
    with_txn = sum(1 for r in rows if r["transaction_id"] is not None)
    ratio = with_txn / len(rows) if rows else 0.0
    print(f"Generated {len(rows)} rows -> {out}")
    print(f"transaction_id present: {with_txn}/{len(rows)} ({ratio:.1%})")


if __name__ == "__main__":
    main()
