"""An unreadable context store must not read as an empty one (AI-83, AI-84).

`context-hub.md` [5]: *"an unavailable context store is indistinguishable from an
empty one, so a model reads 'nothing is defined here' and answers from its own
priors"*. `search_context` did exactly that -- any failure became `hits = []`,
under a comment calling it a resilience path, and the summary then said
"No context found". The sentence the criterion forbids was generated by the
failure it describes.

[6] is the companion: adherence must not be recorded for a caller that did not
itself consult context. The session key folded in the project and stopped there,
so two operators of one project shared a bucket.

These tests drive `core.main` -- the tool the model actually calls -- rather than
the helpers underneath, because both defects lived in the wiring and not in the
pieces.
"""

from __future__ import annotations

import core.main as main
import pytest


class _Boom:
    """A connection factory whose context manager raises on entry."""

    def __enter__(self):
        raise RuntimeError("context store offline")

    def __exit__(self, *exc):
        return False


# --- [5] outage is not emptiness ------------------------------------------


def test_an_outage_summary_refuses_to_say_no_context_was_found() -> None:
    summary = main._build_search_context_summary(
        "revenue", [], "proj_EXAMPLE", store_available=False
    )

    assert "could not be read" in summary
    assert "NOT a statement that no context exists" in summary
    # The exact sentence the criterion forbids must not appear.
    assert "No context found" not in summary


def test_a_genuinely_empty_store_still_says_so() -> None:
    """The other half of the distinction: an answered store with nothing in it."""
    summary = main._build_search_context_summary(
        "revenue", [], "proj_EXAMPLE", store_available=True
    )

    assert summary == "No context found for 'revenue'."


def test_the_default_keeps_the_honest_empty_wording() -> None:
    """Callers that do not pass the flag describe an available store."""
    assert "No context found" in main._build_search_context_summary(
        "revenue", [], "proj_EXAMPLE"
    )


def test_the_tool_reports_an_unreadable_store_on_both_channels(monkeypatch) -> None:
    """The model channel AND the structured envelope must carry the state.

    Both, because they are read by different consumers: the summary is what the
    LLM sees, and `context_store_state` is what a screen or an evaluator reads
    when it needs to ask why `count` is zero.
    """
    import core.db as core_db

    monkeypatch.setattr(core_db, "get_connection", lambda *a, **k: _Boom())
    monkeypatch.setattr(main, "_resolve_project", lambda value, identity=None: "proj_EXAMPLE")

    result = main.search_context("revenue", project_id="proj_EXAMPLE")

    assert "could not be read" in str(result.content)

    envelope = result.structured_content["data"]
    assert envelope["context_store_state"] == "unavailable"
    assert envelope["count"] == 0


def test_a_healthy_read_reports_the_store_as_available(monkeypatch) -> None:
    """`context_store_state` must discriminate, not always say "unavailable"."""
    import core.context_search as ctx_search
    import core.db as core_db

    class _Conn:
        def __enter__(self):
            return self

        def __exit__(self, *exc):
            return False

        def commit(self):
            """Ce que l'appelant fait vraiment depuis AI-157.

            `search_context` commite le sort des candidats ecartes -- sans cette
            methode, le faux levait un `AttributeError` que la branche de
            resilience attrapait, et ce test lisait « magasin indisponible » sur
            une lecture parfaitement saine. Le test etait rouge et decrivait un
            defaut qui n'existait pas.
            """
            return None

    monkeypatch.setattr(core_db, "get_connection", lambda *a, **k: _Conn())
    monkeypatch.setattr(ctx_search, "search_context", lambda *a, **k: [])
    monkeypatch.setattr(main, "_resolve_project", lambda value, identity=None: "proj_EXAMPLE")

    result = main.search_context("revenue", project_id="proj_EXAMPLE")

    assert result.structured_content["data"]["context_store_state"] == "available"
    assert "No context found" in str(result.content)


def test_an_outage_never_marks_the_session_as_having_consulted_context(
    monkeypatch,
) -> None:
    """A failed search must leave the caller non-adherent.

    This was already correct (`if hits:` guards the mark) and is pinned here so
    the [5] repair cannot accidentally start reporting an outage as a successful
    consultation.
    """
    import core.adherence as adherence
    import core.db as core_db

    adherence.reset_for_tests()
    marked: list[str] = []
    monkeypatch.setattr(core_db, "get_connection", lambda *a, **k: _Boom())
    monkeypatch.setattr(main, "_resolve_project", lambda value, identity=None: "proj_EXAMPLE")
    monkeypatch.setattr(
        main, "_mark_context_consulted", lambda *a, **k: marked.append(a[0])
    )

    main.search_context("revenue", project_id="proj_EXAMPLE")

    assert marked == []


# --- [6] the caller who consulted is the caller who is credited ------------


def test_both_adherence_call_sites_pass_the_caller_identity() -> None:
    """AI-84 landed the key in `core.adherence`; this is what activates it.

    A key that folds in an identity nobody passes changes nothing at runtime --
    the defect this repository keeps paying for, one layer up.
    """
    import inspect

    assert "identity=_current_identity()" in inspect.getsource(main._mark_context_consulted)
    # Two: the context mark AND the data-query verdict. One alone would credit
    # the right caller on one side and the wrong one on the other.
    #
    # COUNTED ACROSS THE TWO MODULES THAT HOLD THEM, not across one file: the
    # context mark now lives in `core.agent_surface_mcp` and the data-query
    # verdict in `core.reporting_mcp`. A count taken from `core.main` alone read
    # 2 while both were there and 0 the day they moved -- it never checked the
    # thing it names.
    from core import agent_surface_mcp, reporting_mcp

    sites = sum(
        inspect.getsource(module).count("identity=_current_identity()")
        for module in (main, agent_surface_mcp, reporting_mcp)
    )
    assert sites == 2, sites


def test_an_anonymous_caller_yields_none_rather_than_a_shared_string(
    monkeypatch,
) -> None:
    """Every anonymous caller sharing one identity would rebuild the bug."""
    monkeypatch.setattr(main, "get_access_token", lambda: None)

    assert main._current_identity() is None


def test_an_authenticated_caller_is_identified_by_its_subject(monkeypatch) -> None:
    class _Token:
        claims = {"sub": "person_a"}
        client_id = "client_x"

    monkeypatch.setattr(main, "get_access_token", lambda: _Token())

    assert main._current_identity() == "person_a"


@pytest.mark.parametrize("claims", [{}, {"sub": ""}])
def test_a_token_without_a_subject_falls_back_to_its_client(monkeypatch, claims) -> None:
    class _Token:
        client_id = "client_x"

    _Token.claims = claims
    monkeypatch.setattr(main, "get_access_token", lambda: _Token())

    assert main._current_identity() == "client_x"
